### ISSUE TITLE
Pass cross or tick

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory-website#10]
Up for debate, but if a website hasn't implemented SRI, HPKP, etc... while I don't think they should be penalised, I don't think they should get a tick either... maybe a dash?

![passmarks](https://cloud.githubusercontent.com/assets/1296695/17101130/afb5b7f2-526a-11e6-98df-5fe3789cc9f5.png)

Might also be nice to reinforce the tick or cross with a bit of colour (makes it easier for the eye to scan).

https://github.com/mozilla/http-observatory-website/blob/master/dist/js/httpobs-1.0.0.js#L136

**Comment by marumari** [comment]
This is a brilliant idea.  I was really struggling with it!  I'll work on that today.  :)

**Comment by craigfrancis** [comment]
Thanks April, and no need to rush :-)

Actually, there was one thing I wanted to check, at the moment you are using:

    .glyphicon-ok:before {
        content: "\e013"
    }

I'm wondering if it would be better for the JavaScript to set that value in the DOM, rather than relying on the CSS and Icon Fonts to provide the content.

I know it's being a bit picky, but some users (e.g. using a screen reader with IE11) might have difficulty with this:

http://tink.uk/accessibility-support-for-css-generated-content/

https://speakerdeck.com/ninjanails/death-to-icon-fonts

    $('#tests-cross-origin-resource-sharing-pass').text('✓');

**Comment by marumari** [comment]
I would say to open that as a different bug, but it's a pretty low priority at this point.  Fixing the CSS alone would give me nightmares.  >_<

**Comment by craigfrancis** [comment]
Good point, I've just opened Issue #11 :-)

**Comment by marumari** [comment]
Fixed in b2096b3f60b2ea37b9afe9b16401921a2b8dac0d.  Woohoo!

**Comment by craigfrancis** [comment]
Thanks April :-)

**Comment by marumari** [comment]
Thank you for the great idea!  I really appreciate your participation in this.  :)
