### ISSUE TITLE
Observatory doesn't detect if parent domain is preloaded

### ISSUE THREAD

**Issue by Wonderfall** [mozilla/http-observatory-website#100]
Hi, this seems to be an exception and it gives me headaches. My domain targaryen.house is on the HSTS Preload list and `includeSubDomains` was set.

Observatory sees HSTS from targaryen.house is preloaded : https://observatory.mozilla.org/analyze.html?host=targaryen.house
But it doesn't see HSTS preloading with social.targaryen.house : https://observatory.mozilla.org/analyze.html?host=social.targaryen.house (No - Domain is a subdomain, and can't be preloaded.)

Since HSTS from social.targaryen.house is preloaded, shouldn't it say "Yes, via parent domain" instead of "No"?

Thanks for your time.

**Comment by april** [comment]
The Observatory preload list lags the official a bit.  I just updated the list and this should work fine once the next update is pushed to the backend.  :)

https://github.com/mozilla/http-observatory/pull/228/commits/f155e5faf99891dab88b8612bbc7560b86473874
