### ISSUE TITLE
Unsafe-eval

### ISSUE THREAD

**Issue by digitalhuman** [mozilla/http-observatory-website#101]
Hi,

Unsafe-eval is qually or even more insecure then Unsafe-inline. 'Inline das not have to be insecure per default'.......Unsafe EVAL is per definition insecure. You should fix that.

**Comment by april** [comment]
`unsafe-eval` is only insecure if you're evaling code that you don't have control over.  `unsafe-inline` basically kills all XSS protections, the primary purpose of CSP's restrictions on `script-src`.
