### ISSUE TITLE
Possible to get JSON results back instead of HTML?

### ISSUE THREAD

**Issue by ssx** [mozilla/http-observatory-website#102]
Hi,

I'm looking to automatically run a scan one per month for the sites in my organisations control - is this something that can be done with the web version with an accept-header or doable with the CLI version?

**Comment by ssx** [comment]
Ignore, just found the API docs and link!

**Comment by april** [comment]
Sounds good.  Let me know if you have any trouble.  You can also use local scans and the local CI functions to easily scan sites inside your organization that have no inbound internet connection.  :)
