### ISSUE TITLE
User survey for Observatory

### ISSUE THREAD

**Issue by april** [mozilla/http-observatory-website#103]
It would be great to know what kind of people use the Observatory (and its website), what they're wanting, and what they struggle with.  In conjunction with @gregglind, I would like to do a survey to find this sort of information out.

Things I would like to know:

**Who uses the Observatory?**
- Management
- Web developers
- Security people
- Highly empowered randos
- Meta-site operators (ala the Mozilla Dashboard)

**What do people want us to focus on?**
- Better UI/UX
- More security tests / more fleshed out tests
- More 3rd party integrations
- More documentation
- Something else entirely

**What do they struggle with?**

**What do they find most useful?**

Places we could put this:
- Top of the website as a banner
- In the FAQ/help documentation
- GitHub page
- Mozilla announcement

**Comment by jeffbryner** [comment]
Here's some thoughts: 
For the survey, should probably have an 'other' answer for each question for free form thoughts. 

How about a section for 'best next feature'? 
1) Integration with devtools
2) Integration with MDN
3) More standalone guides (how to stand up yer own
4) other?
