### ISSUE TITLE
Add tick/cross marks in DOM

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory-website#11]
At the moment you are using:

```
.glyphicon-ok:before {
    content: "\e013"
}
```

I'm wondering if it would be better for the JavaScript to set that value in the DOM, rather than relying on the CSS and Icon Fonts to provide the content.

I know it's being a bit picky, but some users (e.g. using a screen reader with IE11) might have difficulty with this:

http://tink.uk/accessibility-support-for-css-generated-content/

https://speakerdeck.com/ninjanails/death-to-icon-fonts

```
$('#tests-cross-origin-resource-sharing-pass').text('✓');
```

**Comment by marumari** [comment]
Whoops, meant to say that it fixes #10.  :(

**Comment by floatingatoll** [comment]
To clarify, will the screen readers *fail* to speak that particular icon, or will they break in some sort of manner that impacts reading out the rest of the content?

If they'll be read out the test name and the score, while silently discarding the icon, that is a far better case than having the reader fail entirely when it encounters the page.

**Comment by craigfrancis** [comment]
I believe they simply don't read the content (more so IE11), unfortunately I don't have access to my VMs to test at the moment.

Overall it's not terrible, but the tick/cross/dash is useful to have, especially as you would be navigating a table, with a column that is empty (making you wonder what you're missing).

Should also add, the new "0 dash, not implemented, but that's fine" (e.g. SRI) is quite different to the "0 tick, thing has been implemented, but you don't get any plus points" (e.g. cookie flags).

**Comment by floatingatoll** [comment]
When you talk about the "0 dash" vs "0 tick" thing, is that a problem specific to the screenreader issue here, or are you describing a separate issue (and if so, has it been filed already)?

**Comment by craigfrancis** [comment]
Not screen reader problem, it's how the scores are shown, where it would be useful to everyone to see the content of the "Pass" column.

See Issue #10 for more info:

https://github.com/mozilla/http-observatory-website/issues/10

Basically the dash is a new (ish) state that differentiates between a 0 being a "this thing hasn't been implemented, but that's fine" and the tick to say "everything has been done, but you're not getting any plus points for it" :-)
