### ISSUE TITLE
Allow SSH observatory results to return in cases where no HTTP services

### ISSUE THREAD

**Issue by claudijd** [mozilla/http-observatory-website#114]
Current behavior is that the scan is tasked, but not displayed.

**Comment by claudijd** [comment]
Reproduction example:

https://mozilla.github.io/http-observatory-website/analyze.html?host=ssh.mozilla.com

**Comment by april** [comment]
This was fixed, woo.

**Comment by claudijd** [comment]
👍

**Comment by april** [comment]
Reopening this, because there's a bug on the home page that prevents you from scanning a site that is down.
