### ISSUE TITLE
Display SSH auth methods in SSH Observatory

### ISSUE THREAD

**Issue by claudijd** [mozilla/http-observatory-website#116]
I think it would be helpful for people to see what auth_methods are in use as a first class citizen displayed on the SSH observatory tab.

**Comment by april** [comment]
It will tell them to remove them if there are recommendations to do so, do you want me to display them even if they currently meet recommendations?

**Comment by april** [comment]
Fixed in 22cea83d9c82b2c4225b238851ea3950f4ef2b70.
