### ISSUE TITLE
Display policy reference URL in SSH Observatory

### ISSUE THREAD

**Issue by claudijd** [mozilla/http-observatory-website#117]
I provide policy reference URLs for scan results in ssh_scan_api, can we provide a landing location that points users to this URL so we can get them more docs on how do what we're asking?

**Comment by april** [comment]
It already does this, I think?  Under Mozilla SSH Standards Compliant?  Perhaps it's not clear enough though?

**Comment by claudijd** [comment]
Yeah, I just realized that.  Perhaps we could put something in there that says "Go over here for help" in recommendations section or something.  That URL field is intended for users to customize, but in this implementation, it will always point to the Mozilla guidelines.
