### ISSUE TITLE
Display IP's and/or hostnames of servers that are used to scan SSH (SSH observatory)

### ISSUE THREAD

**Issue by Razerwire** [mozilla/http-observatory-website#118]
Some users use iptables / or some firewall to limit access to port 22 (SSH). 
Displaying the IP addresses and/or hostnames of the server(s) that is / are used for scanning SSH,  allows the end user to temporarily allow those IP adresses to access port 22 so that scanning may take place.

**Comment by april** [comment]
Hmm, thanks for the idea. I'll have to figure out how to implement this -- perhaps when it fails?

**Comment by Razerwire** [comment]
You're welcome. Displaying IP's or hostnames when the SSH scan fails sounds reasonable. 
The timeout is 30 seconds, right?

**Comment by april** [comment]
It's currently 15 seconds.  In any case, I'll add a notice about it to the SSH Observatory scan page.  :)
