### ISSUE TITLE
Add a "request rescan" button to the individual results page

### ISSUE THREAD

**Issue by edmorley** [mozilla/http-observatory-website#12]
**STR:**
1) Visit eg https://mozilla.github.io/http-observatory-website/analyze.html?host=treeherder.mozilla.org from a link in a bug/email
2) Make some changes to improve the score
3) Revisit that URL to see updated score

**Expected:**
Obvious way to request a rescan from that page.

**Actual:**
No way to rescan from there, I have to return to the homepage (https://mozilla.github.io/http-observatory-website/), enter the domain name again and choose "Force a rescan".

**Comment by marumari** [comment]
This shouldn't be too difficult to do.  Note that we force a minimum cooldown time of 180 seconds, even for rescans.

You may also want to use the command line tool:

# pip install httpobs-cli
$ httpobs -r treeherder.mozilla.org

**Comment by edmorley** [comment]
Awesome, thank you :-)

**Comment by marumari** [comment]
You've very welcome.  Thanks for the idea!
