### ISSUE TITLE
Different scores when caching enabled

### ISSUE THREAD

**Issue by cjc1867** [mozilla/http-observatory-website#120]
Hi April
Great website but I get 2 different set of results when I have a caching plugin installed. At first I got 'D' then delete the cache I got 'B+'.

I have experienced this on another similar website that does a similar scan with the headers.

I am using WP Super Cache and HTTP headers.

So if I get a 'D' from your website then does that mean I am not protected? If I delete the cache and get B+ then surely my website looks like it is protected but is it?

All this web security is new to me and I have tried to follow best practices but if I am getting different results all the time then I don't know if my site is secure or not.

Need more information then please contact me.

Cheers

Colin

**Comment by cjc1867** [comment]
Hi April
I enabled WP Super Cache and used http://www.webconfs.com/http-header-check.php it gave some or little amount of information but I disabled it and rescanned and it gave me a lot more information. Well it gave the information I am interested in and should be displayed on your website.

So now it looks like WP Super Cache is conflicting with HTTP Headers Plugin, need to get in touch with the latter and see if there are any problems.

But if this is an issue other website owners will not get the results they expect and that could have a negative impact on your website as well as Scott's.

Colin

**Comment by cjc1867** [comment]
Hi April
Yes there is a problem with both plugins and it's not your website. Clearing the cache every time is not the answer, it means there isn't any security which defeats the object of what I am trying to do.

Take a look here please:
https://wordpress.org/support/topic/the-plugin-doesnt-change-my-cache-headers/#post-9285477

I don't think I will be using a caching plugin again, they cause too many problems.

Anyhow if other users of your website have similar issues then it will be the same caching plugin or another conflict.

thanks
Colin

**Comment by cjc1867** [comment]
Hi April
I have been trying other plugins and found this https://wordpress.org/support/topic/caching-plugin-6/
So there is a problem but not from your website, that explains why I am getting inconsistent results.

Cheers

Colin

**Comment by floatingatoll** [comment]
Thanks for letting us know! Much appreciated.
