### ISSUE TITLE
Scoring guide needs to be updated for extra credit change

### ISSUE THREAD

**Issue by Razerwire** [mozilla/http-observatory-website#122]
This morning I've tested [https://www.bonnieradvocaten.nl](https://www.bonnieradvocaten.nl) with the Observatory. 

To my dismay our score dropped from 85/100 (A-) to 75/100 (B).

It seems that, when calculating the total score,  the observatory doesn't take into account the use the Referrer-Policy "no-referrer" which should raise the total score with +5 points, furthermore the use of XFO via CSP (which should account for +5 points)  is ignored when calculating the total score.

**Comment by Razerwire** [comment]
Moving this to the right repository... Sorry

**Comment by floatingatoll** [comment]
I think you were on the right track here - this is due to a scoring algorithm change, where if you have more than -10 in penalties, you can't get +X boosts. The scoring guidelines page on the site needs updating (per mozilla/http-observatory#252) and so this is a good bug for that.

**Comment by april** [comment]
Thanks for letting me know! I made the change last week but kind of ran out of time for updating the documentation. I will definitely make sure that I get the documentation updated this week.

**Comment by Razerwire** [comment]
@april 
The scoring methodology page still needs updating, you didn't forget about this did you?

**Comment by april** [comment]
Oh, shoot.  I fixed the FAQ in commit e89cf1b0ecb85f18fa48ea372decdbe748b43ad7 over a week ago, I should update the scoring methodology page as well. Thanks for letting me know.
