### ISSUE TITLE
Unable to scan IP addresses from main page

### ISSUE THREAD

**Issue by fishouttah20** [mozilla/http-observatory-website#123]
Scan my site blocks the scanning of IP addresses. This was ok with HTTPS but now that SSH is available to scan, many such hosts don't have registered domain names.

This can be bypassed by /analyze.html?host=x.x.x.x#ssh but ideally this could be done through the UI.

**Comment by claudijd** [comment]
The ssh_scan_api endpoint supports this, it's simply a restriction on the http-observatory-website to only scan hostnames currently.

Here's a poor mans work-around client without the restriction, but minus all the friendly interface of the Observatory...

https://blog.rubidus.com/ssh_scan_client.html?target=sshscan.rubidus.com

You can also use any of the clients here...

https://github.com/mozilla/ssh_scan_api/tree/master/examples

**Comment by floatingatoll** [comment]
Unfortunately, Mozilla Observatory will not be (intentionally) providing a public service for "scan an IP address", so I filed issue #124 to extend the restriction to the `?host=x.x.x.x#ssh` parameter as well. Thank you for uncovering this issue, and I'm sorry that our stance is incompatible with your wishes here.

**Comment by april** [comment]
The HTTP Observatory still (and will always) block IP addresses and it does so even when you go directly to the URL. There was never a need to change the public behavior, since IP addresses don't really work with TLS or HTTPS.

Now that we have SSH, I think this is the correct behavior, but we need to be clear about the limitations.

**Comment by floatingatoll** [comment]
Oh, neat. TIL and apologies for misspeaking!

**Comment by april** [comment]
This was fixed, just forgot to close.  :)
