### ISSUE TITLE
Scan ID link in SSH Observatory is broken

### ISSUE THREAD

**Issue by caggle** [mozilla/http-observatory-website#129]
When an SSH scan is performed on a host with SSH Observatory tab, a Scan ID is returned with a link, that is supposed to point to the raw JSON output of ssh_scan tool for that host.

The link is generated wrong however; for instance a URL in the following format is generated for a Scan ID: 
https://observatory.mozilla.org/undefinedscan/results?uuid=<ssh_scan UUID>

whereas the following should have been generated:
https://sshscan.rubidus.com/api/v1/scan/results?uuid=<ssh_scan UUID>

**Comment by april** [comment]
Thanks for letting me know! Should be fixed time I deploy to the website in the next day or so.  :)
