### ISSUE TITLE
possible to trigger endless loop

### ISSUE THREAD

**Issue by jonassmedegaard** [mozilla/http-observatory-website#130]
Seems I just now accidentally triggered a denial-of-service attack:

I misconfigured my host to redirect to https unconditionally (meant to do so only when accessing http) causing an endless loop at my website.

Firefox detects and breaks such loops, but apparently your javascript code does not.

**Comment by april** [comment]
It should automatically detect them, as that's part of redirects. Can you send me an example of this happening?

**Comment by april** [comment]
If I run the local scan, here is what it gives me:

```python
>>> from httpobs.scanner.local import scan
>>> scan('misbehaving.site', path='/redirect-loop/0')
{'error': 'site down'}
```

But it's possible that there is something about the live version that isn't working.
