### ISSUE TITLE
Do not report missing `base-uri` directive if it is present in the policy

### ISSUE THREAD

**Issue by shekyan** [mozilla/http-observatory-website#131]
Getting `Restricts use of the <base> tag by using base-uri 'none', base-uri 'self', or specific origins`

while analyzing [cspvalidator.org](https://observatory.mozilla.org/analyze.html?host=cspvalidator.org)

**Comment by april** [comment]
It looks fine to me. I suspect what happened here is that you were looking at a cached scan result, before it started scanning for `base-uri`. I initiated a rescan and the results are all there as you would expect.  :)
