### ISSUE TITLE
Referrer-Policy set to "no-referrer", but still shown as "unsecure"

### ISSUE THREAD

**Issue by Dremor** [mozilla/http-observatory-website#133]
https://observatory.mozilla.org/analyze.html?host=lab.dremor.info

The raw header part show that the Referrer-policy header is set to "no-referrer", but the test still give me a -5.

**Comment by floatingatoll** [comment]
Your HTML response page contains a second Referrer header with a -5 value. Removing this <meta> tag should resolve the issue you're encountering.

```html
<meta content="origin-when-cross-origin" name="referrer">
```
