### ISSUE TITLE
not having contributors.md dings points, despite having nothing to do with security

### ISSUE THREAD

**Issue by Pomax** [mozilla/http-observatory-website#134]
Right now sites get 10 points for having a contributor.md, despite the fact that for security purposes this file is not relevant - it's certainly a good thing to have for an open source project, and definitely worth flagging as part of a codebase analysis, but observatory seems the wrong place to slip that in: it does not impact security, and so having one, or not having one, should not affect the security rating of a site.

**Comment by floatingatoll** [comment]
For security purposes, a guideline for potential contributors in a
well-known filename is invaluable. Having contribution guidelines improves
the likelihood of security issues being reported to and fixed by a project
successfully.

**Comment by Pomax** [comment]
On an publicly visible code repository, absolutely (github etc immediately spring to mind), but for a normal website I don't see how this would be true given a large enough number of privately developed websites. Is there a spec/rfc that this decision was based off of? If not, this would be one of those things you don't want to count towards the security rating, but count separately as "best practice bonus points" (having this file should not make the difference between an A or a B, for instance, but between an A and an A with open source bonus points)

**Comment by floatingatoll** [comment]
Note that you can't score any bonus points [+10] unless your site has zero
negative points [-XX] of any form anywhere in its scan results. (I'm not
sure what the minimum score without negatives is, April might know.)

**Comment by Pomax** [comment]
In that case this still needs a different treatment because that _file_ does not make things more or less secure. It should count towards as (separate) best practices rating, not towards the _security_ rating,

**Comment by floatingatoll** [comment]
Thanks for taking the time to explain your desires here. The observatory
intentionally uses a single cumulative rating to represent best practices —
for user privacy, for web security, and for operator accountability. The
only “maximum” score to achieve is to get an “A” letter grade; everything
else is extra credit.

When seeking a high score on the Observatory, I encourage only pursuing
bonuses that you consider reasonable and appropriate for your
circumstances. If you don’t see the value in CONTRIBUTORS.md, then you
should not use it, and the site will neither grant you extra credit nor
penalize you.

Few (if any) sites receive every possible site, and not every bonus makes
sense for every site. For example, I previously deployed SRI to one of our
internal sites to receive an Observatory bonus, but in hindsight no actual
improvement for users occurred as a result of my work (all scripts were
onsite, https, and HSTS) and it eventually was removed.

In general, sites are expected to address all negative scores, and then may
optionally choose to pursue certain bonuses. Sites cannot universally
implement all bonuses, as many of them conflict with operational decisions
— subdomains can’t HSTS Preload, HPKP is risky for average site operators,
and sometimes site operators simply disagree with the steps necessary to
earn a bonus.

**Comment by Pomax** [comment]
Okay, but allow me to counter that by saying that even if your _intention_ is as stated, companies out there in the world are literally telling their engineers that one of the requirements is to score an A, even if it's a private website. Treating the absence of this file as negative points is not a nice thing to do: hundreds of thousands of websites don't have the luxury to include one.
