### ISSUE TITLE
Favicon redirects to non-listening port

### ISSUE THREAD

**Issue by claudijd** [mozilla/http-observatory-website#138]
Repro: curl -k -i https://observatory.mozilla.org/images/favicons

Basically, https://observatory.mozilla.org/images/favicons redirects to http://observatory.mozilla.org:58443/images/favicons/ (the internal listening port, which is not publicly accessible)

**Comment by claudijd** [comment]
Discovered via https://github.com/zaproxy/zaproxy/issues/4171

**Comment by april** [comment]
Fixed in https://github.com/mozilla/ansible-eis/commit/029afd2c4d68120718fa2ae1bc757184e736c181. I should be able to fix the bounce back to http once nginx is updated to 1.11.
