### ISSUE TITLE
Error: AttributeError("'module' object has no attribute 'JSONDecodeError'",)

### ISSUE THREAD

**Issue by leonklingele** [mozilla/http-observatory-website#14]
Was scanning my [site](https://www.leonklingele.de/) and got this error message:
`Error: AttributeError("'module' object has no attribute 'JSONDecodeError'",)`

**Comment by marumari** [comment]
Hmm, that's strange.  I'll take a look into it.  Thanks!

**Comment by marumari** [comment]
Fixed in https://github.com/mozilla/http-observatory/pull/86.  You should be able to see your scan results now.  :)
