### ISSUE TITLE
CSP warning visiting observatory.mozilla.org

### ISSUE THREAD

**Issue by edmorley** [mozilla/http-observatory-website#142]
If I visit https://observatory.mozilla.org/ in Firefox Nightly, in the console I see:
```
17:38:14.986 Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src"). Source: ;!function(){var t=0,e=function(t,e){ret....
17:38:14.986 Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src"). Source: call to eval() or related function blocked by CSP.
```

**Comment by floatingatoll** [comment]
I couldn't trigger this error in Chrome 64. Ed, does it occur in release as well, or only nightly?

**Comment by edmorley** [comment]
Ah so it turned out the CSP is being violated by scripts injected by add-ons (in this case, LastPass and NoScript). So this is a combination of [bug 1323478](https://bugzilla.mozilla.org/show_bug.cgi?id=1323478) and [bug 1267027](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027).

Sorry for the noise! (And I really hope those browser bugs get fixed soon...)
