### ISSUE TITLE
SRI scoring on scriptless websites

### ISSUE THREAD

**Issue by zakius** [mozilla/http-observatory-website#144]
Hey, I'm not sure how I feel about this and if it is intended or not, but if website loads exactly zero scripts it loses (or doesn't gain to be precise) extra 5 points assigned for proper use of SRI

On one hand I am aware that it doesn't mean my score is not perfect, just the grading system is not meant for such an extreme cases, but possibly it could get changed cause I still lack the satisfaction provided by perfect score

And I can even vouch for the idea of assigning these 5 points for lack of scripts: since there are no scripts none can get replaced with malicious versions

Besides that the description I get is "Subresource Integrity (SRI) not implemented, but all scripts are loaded from a similar origin" suggesting that I indeed loaded some scripts, just these were loaded from (sub)domain of my website, this seems to be mistake

**Comment by floatingatoll** [comment]
This may relate to the last comment in issue #2.
