### ISSUE TITLE
Page rendered before CSS is available

### ISSUE THREAD

**Issue by gene1wood** [mozilla/http-observatory-website#145]
Each time the observatory is loaded, the page renders before the CSS is available. On fast connections this flashes by but on slower ones it would render oddly for longer.

![mozilla-observatory-missing-css](https://user-images.githubusercontent.com/1134034/35759673-f66c3e74-082f-11e8-9d36-8216bcebada5.png)

Here's a video of what it looks like

[![Mozilla observatory page rendered before CSS is available](https://img.youtube.com/vi/34zC472YJq0/0.jpg)](https://www.youtube.com/watch?v=34zC472YJq0)

(This is copied from mozilla/http-observatory#322 as this is probably the right repo for this issue)

**Comment by floatingatoll** [comment]
Observatory loads a static CSS file initially (css/httpobs.*.css) and then loads a variety of JS files which are needed to apply the remaining styles to the page. So what you're seeing may not be "unstyled" content, but instead "styled" content that hasn't yet been JS-processed into the final result.

The static resources should be cached after the first page load, unless your Network Inspector pane is open with Disable Caching set. Do you see this frequently on the site?

**Comment by april** [comment]
This was fixed with the latest updates.

**Comment by gene1wood** [comment]
Yup, works right now, thanks!

**Comment by april** [comment]
FYI, it was a regression in Firefox that caused this particular issue, but that has been fixed as has the layout situation that caused it to happen in the first place.
