### ISSUE TITLE
TLS tab should display validity information.

### ISSUE THREAD

**Issue by jvehent** [mozilla/http-observatory-website#148]
When a certificate is not valid for a given origin, or uses a root that is not trusted, TLS Observatory returns `is_valid: false` in the scan results. This information should be displayed on the TLS tab to inform the user that the site is not trusted.

ref: https://github.com/mozilla/tls-observatory/issues/310

**Comment by april** [comment]
This was fixed in c166ed86a75ab0a60eed978923e8a7d17b284bb7 and is now in production:

https://observatory.mozilla.org/analyze/webassembly.org#tls
