### ISSUE TITLE
-10 for not having a contribute.json? Really?

### ISSUE THREAD

**Issue by leonklingele** [mozilla/http-observatory-website#15]
From the website: `The Mozilla Observatory is a project designed to help developers, system administrators, and security professionals configure their sites safely and securely.`

The docs say `contribute.json is a Mozilla standard used to describe all active Mozilla websites and projects.` – Why do I need to have a `contribute.json` if I do not host a Mozilla website? :wink:

**Comment by marumari** [comment]
You don't.  If you remove the file, you'll notice that you don't get penalized for it.  It's only because you have one *and* it's malformed that you get penalized.  :)

**Comment by leonklingele** [comment]
OK, that makes sense. :)
What if my website has its own, non-Mozilla-compliant `contribute.json`?
I then get an error saying `-5, Contribute.json exists, but is missing some of the required keys`.
That's not a problem for me, but wouldn't it make sense to only display a warning instead of penalizing the score?
