### ISSUE TITLE
no-third-party checkbox breaks TLS scanner tab

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory-website#150]
Steps to reproduce:

1. Enter a valid domain into the hostname field
2. Check only the box "don't use third party scanners"
3. Initiate scan.
4. Take note of the &third-party=false fragment shown on the HTTP tab.
5. Switch to the TLS tab.

The underlying issue here is likely that the query params need to open with ? rather than & as the resulting URL from 3. above is:

https://observatory.mozilla.org/analyze/www.mozilla.org&third-party=false

**Comment by april** [comment]
This was fixed some time ago, but I have no idea when.  :)
