### ISSUE TITLE
analyze.html without arguments shows up in Google results

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory-website#151]
https://observatory.mozilla.org/analyze.html

This specific URL is indexed by Google and breaks upon loading. Unless it's desirable for Google to index all possible `/analyze.html?arg=arg` results, consider excluding this path from indexing altogether using robots.txt or other means.

**Comment by april** [comment]
It's now `/analyze/mozilla.org`, which I think is fine. Do you think these should be excluded?

**Comment by floatingatoll** [comment]
My only concern is that the top google result leads to a broken page — as
long as analyze.html isn’t a result anymore, I’m happy!

**Comment by floatingatoll** [comment]
Still broken today. Also, note how a third party website is on the first page of results. This is the results I’d like us to improve in this issue:

![139c0f1d-0446-416f-abef-455edd4a91fc](https://user-images.githubusercontent.com/92684/40936185-64b356f0-67ef-11e8-9f6a-4edb17095db7.png)

**Comment by april** [comment]
This should work as robots.txt, right?

```
User-agent: *
Disallow: /*.html$
```

**Comment by floatingatoll** [comment]
I’m not sure $ is valid without regexes, which ‘/*’ isn’t. Otherwise, yes,
should help.

**Comment by april** [comment]
It's based on what I got here:
https://moz.com/learn/seo/robotstxt

**Comment by floatingatoll** [comment]
That trailing $ really bugs me, but if it’s real, I guess?

**Comment by floatingatoll** [comment]
`/*.html$` makes sense based on that SEO file, and matches Google's [docs](https://developers.google.com/search/reference/robots_txt). You are right, that's the best plan.

**Comment by floatingatoll** [comment]
This change was included in 4c9d300ec5666de504b32d44e18fdd2ea9190b5d (perhaps by accident), and the broken analyze.html no longer appears in the search results! Thank you so much for this.
