### ISSUE TITLE
"script-src 'strict-dynamic'" results in "Content Security Policy (CSP) header cannot be parsed successfully"

### ISSUE THREAD

**Issue by timball** [mozilla/http-observatory-website#155]
I am attempting to set the `strict-dynamic` directive for `script-src` and the observatory always returns "Content Security Policy (CSP) header cannot be parsed successfully"

my CSP is set as:
``
Content-Security-Policy: default-src 'none'; frame-ancestors 'none'; object-src 'none'; require-sri-for script style; base-uri 'self'; form-action 'self'; script-src 'strict-dynamic'; report-uri https://that-place-that-i-put-the-reports/;
``
which i *think* is fine, but the computers say that's wrong. I think the computers are wrong. 

i note that if I change the CSP to:
``
Content-Security-Policy: default-src 'none'; frame-ancestors 'none'; object-src 'none'; require-sri-for script style; base-uri 'self'; form-action 'self'; script-src 'self'; report-uri https://that-place-that-i-put-the-reports/;
``
everything is fine and passes. 

--timball

**Comment by floatingatoll** [comment]
That directive must be accompanied by a nonce or hash declaration in the
script-src clause. Does adding one resolve the parsing failure?

**Comment by april** [comment]
That's almost certainly why it generated that error. You must include a nonce with `'strict-dynamic'`.
