### ISSUE TITLE
X-Content-Type-Options header cannot be recognized

### ISSUE THREAD

**Issue by nhansum** [mozilla/http-observatory-website#157]
The result of scanning our website www.tangram-tis.nl scored -5 on X-Content-Type-Options, saying "X-Content-Type-Options header cannot be recognized". 
Yet the Raw Headers sections shows "X-Content-Type-Options nosniff".

**Comment by nhansum** [comment]
Can you offer an explanation on the issue I'm experiencing?

**Comment by april** [comment]
I think I know what the issue is (there's an extra space after `nosniff`), but I'll take a look on Monday and see if that's exactly what's happening.

**Comment by april** [comment]
Fixed and deployed. Thanks for letting me know!

https://observatory.mozilla.org/analyze/www.tangram-tis.nl
