### ISSUE TITLE
Odd ciphersuite names

### ISSUE THREAD

**Issue by martinthomson** [mozilla/http-observatory-website#158]
I realize that these are probably what OpenSSL spits out, but what is "AES128-GCM-SHA256" ?  It is labelled as being a TLS 1.2 suite, but all TLS 1.2 suites include an authentication scheme and the corresponding key size is 2048, so I'm assuming that RSA is involved somehow.  Is it TLS_RSA_WITH_AES_128_GCM_SHA256?

Can this use the names from the standard?

**Comment by april** [comment]
Sorry, for some reason I didn't get a notification about this. This is actually the name that OpenSSL uses for the cipher suite. I also think it's a questionable choice, especially since they don't drop the KEX with any other cipher suites.

**Comment by april** [comment]
Fixed and deployed:
https://observatory.mozilla.org/analyze/google.com#tls

Thanks, @martinthomson.
