### ISSUE TITLE
Subsresource Integrity incorrect score

### ISSUE THREAD

**Issue by paulgoodfield** [mozilla/http-observatory-website#160]
When scanning a site we're working on, the Subresource Integrity score is currently showing as **-50**, indicating that external scripts are not loaded over https. However, when viewing the site in Chrome and viewing the **Network** tab in dev tools, the **Scheme** column shows that all resources are being loaded over https.

If you need to know the specific site, I can email you the domain.

**Comment by april** [comment]
Yes, if you want to email me the specific domain, I'd be happy to take a look at it. I'm april@mozilla.com.

I'll add that there's a good chance that Chrome only showed HTTPS because the site was HSTS loaded (or preloaded), but the link itself was HTTP. Happy to take a look, however. Thanks!

**Comment by floatingatoll** [comment]
Does your site use `src="//`? If so, that counts as http:// for various
reasons, and needs to be revised to https://.

**Comment by april** [comment]
Yup, this is exactly what it is. You're loading scripts like this:

`<script src="//code.jquery.com/jquery-2.2.4.min.js">`

If you change this to `https://code.jquery.com/jquery-2.2.4.min.js`, then this should be fixed. There's no reason to use `//code.jquery.com/jquery-2.2.4.min.js` for remote content available over HTTPS, as it gives a MITM another opportunity to inject content for your users.

**Comment by paulgoodfield** [comment]
@april @floatingatoll That worked - thanks so much for your help both!
