### ISSUE TITLE
htbridge.com tests does not seem to be working anymore

### ISSUE THREAD

**Issue by stof** [mozilla/http-observatory-website#163]
When accessing the third-party tab, I always see it as `PENDING (This may take several minutes)`. But looking at the dev tools, the HTTP request already returned a response about test being cached:

```json
{"test_id":"[redacted]","status":"test_cached","status_id":3,"message":"Test is cached"}
```

Looking at the code at https://github.com/mozilla/http-observatory-website/blob/fbe20de79820aeb5b9fd66671943f09c8d6720f3/js/httpobs-third-party.js#L174-L226, it looks like it is expected to get more info in this JSON

**Comment by april** [comment]
This was fixed in the big update to webpack, and es6, and modules and what not.  :)
