### ISSUE TITLE
Please consider removing off-site resources from the Observatory website.

### ISSUE THREAD

**Issue by beerisgood** [mozilla/http-observatory-website#166]
From https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fobservatory.mozilla.org%2F
**8** third-party requests to 4 unique hosts (cdnjs.cloudflare.com ; maxcdn.bootstrapcdn.com ; fonts.googleapis.com ; fonts.gstatic.com)

You should remove Google from your testsite for privacy reasons:

> The site loads fonts from Google Fonts. While these are hosted on resource-specific domains and no cookies are sent, Google could possibly cross-reference the data (IP and browser fingerprint) with other Google services to identify visitors. Do they? Their own [FAQ](https://developers.google.com/fonts/faq?hl=en#what_does_using_the_google_fonts_api_mean_for_the_privacy_of_my_users) is vague: "We do log records of the CSS and the font file requests, and access to this data is on a need-to-know basis and kept secure." What "need-to-know basis" means is not explained.

**Solution:** Fonts can easily be self-hosted. The tool [google-webfonts-helper](https://google-webfonts-helper.herokuapp.com/fonts) lets you select one or more fonts, generates the proper CSS and prepares a zip file with the fonts. For a command-line alternative, the shell script [google-font-download](https://github.com/neverpanic/google-font-download) provides similar functionality.

Also: 

> The site is loading libraries from one or more CDN:s.

**Solution:** Self-host the files.

**Comment by beerisgood** [comment]
*push*

**Comment by april** [comment]
This was done with the conversion to webpack and everything.  :)

**Comment by beerisgood** [comment]
Awesome!
