### ISSUE TITLE
x-content-type-options only for script and css requests only?

### ISSUE THREAD

**Issue by nuxodin** [mozilla/http-observatory-website#167]
According to the sonarwhal.com documentation, the "x-content-type-options" header is only used as headers for script and css files, not the html file.

"x-content-type-options requires that all scripts and stylesheets are served with the X-Content-Type-Options: nosniff HTTP response header."

https://sonarwhal.com/docs/user-guide/rules/rule-x-content-type-options/

**Comment by floatingatoll** [comment]
Sonarwhal is incorrect. Chrome uses the X-CTO response header on HTML and other documents to activate security features not addresses by Sonarwhal’s explanations. More discussion is available at mozilla/http-observatory#341 if you wish to review and/or comment there.

**Comment by nuxodin** [comment]
Thank you for your answer!
