### ISSUE TITLE
Unable to avoid Secure cookies penalty due to shared hosting load balancer cookies

### ISSUE THREAD

**Issue by githubhero** [mozilla/http-observatory-website#171]
Not exactly "an issue", but: I see you get -5 if your cookies are not Secure ("Cookies set without using the Secure flag, but transmission over HTTP prevented by HSTS"). My website serves two cookies but I have absolutely no control over both cookies because they are directly served by the (shared) hosting infrastracture, I suppose in the context of load balance activities. I can't neither override them through htaccess, for example. 

I suppose there's no way for you to know what originated the cookies, if they are really potentially harmful and if they could be eventually served over https.

**Comment by april** [comment]
Yeah, unfortunately there's no way to know. We currently have a carve-out for Cloudflare (since they're so popular), but even that should be going away soon. Sorry!
