### ISSUE TITLE
Support scanning of subdirectories

### ISSUE THREAD

**Issue by bigbgh** [mozilla/http-observatory-website#177]
I have a domain where the base URL acmewidgets.com has a redirect to acmesales.com
The page I want to scan is acmewidgets.com/login
However, when I try to scan this URL it only scans the base URL, ignoring the subdirectory.
Please allow scanning of subdirectories, or if it is already possible, explain how.

**Comment by april** [comment]
For some reason, I didn't get notification of this particular issue. We don't allow scanning of subdirectories from the public domain for security reasons, but all of the Observatory tooling does support it underneath.

**Comment by Jieiku** [comment]
How can I enable the feature on my local install of observatory, It took me a couple days to get it all up and running, but it seems to have the same problem.

```bash
/usr/bin/node /home/jake/observatory-cli/index.js netoun.github.io/ntun --zero --format=report

observatory [ERROR] Unable to get result. Host:netoun.github.io/ntun Error:invalid-hostname.
```

If I omit the subdirectory then it seems to work without issue, but this is not a valid test for some sites that use shared hosting.

**Comment by Jieiku** [comment]
That was actually much easier than I thought, All I had to do was comment out that line in `httpobs/website/api.py`

```py
hostname = valid_hostname(hostname) or valid_hostname('www.' + hostname)  # prepend www. if necessary
```
