### ISSUE TITLE
Update to DNS verified certificate

### ISSUE THREAD

**Issue by gene1wood** [mozilla/http-observatory-website#181]
I've provisioned the ACM certificate

```
arn:aws:acm:us-east-1:371522382791:certificate/6af2a7fe-1b77-4a57-89cf-a5572325fb3f
```

in infosec-prod

Would you update your provisioning code to use this instead of the current email validated ACM cert?

(Relates to [Bug 1516434](https://bugzilla.mozilla.org/show_bug.cgi?id=1516434))

**Comment by april** [comment]
I don't really have any provisioning code? It's behind an ELB, and I just used the AWS interface to request / renew certs.  :)

**Comment by gene1wood** [comment]
@april How do you provision the ELB (e.g. ansible, cloudformation, terraform, manual web console)?

**Comment by april** [comment]
Just the manual web console. It didn't seem important enough to automate, especially since I just had to do it once (or twice, I don't remember).

**Comment by gene1wood** [comment]
Ok
