### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/http-observatory-website#183]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/http-observatory-website/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by HarshCic** [comment]
wiki page of https://github.com/mozilla/http-observatory-website/issues/183 repo is not accessible.

**Comment by moz-hwine** [comment]
The wiki was enabled and protected. Since it was empty, I just disabled the wiki. All good here.
