### ISSUE TITLE
ssl_ecdh_curve and nginx breakage

### ISSUE THREAD

**Issue by storrgie** [mozilla/http-observatory-website#184]
It appears that if you specify,
```
ssl_ecdh_curve X25519;
```
in nginx then observatory cannot make the scan, where third parties can.

**Comment by april** [comment]
Is this in the TLS section or in the HTTP section?

**Comment by storrgie** [comment]
It's in the `server` section, the entire block for ssl configurations was this:

```
ssl_session_timeout 10m;
ssl_session_cache shared:SSL:64m;
ssl_session_tickets off;
add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload";

ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 1.0.0.1 valid=60s;
resolver_timeout 5s;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers EECDH+CHACHA20:EECDH+AES;
ssl_ecdh_curve X25519;
ssl_prefer_server_ciphers on;
```

**Comment by april** [comment]
No, I mean which section of the Observatory website. Is it the HTTP tab that doesn't show results, or the TLS tab?

Thanks!

**Comment by storrgie** [comment]
Ah sorry, it's the first tab, literally says "Test failed" (or something like that)

**Comment by april** [comment]
Huh, that's strange. Could you share a domain I could test this with? If you're not comfortable sharing it in public, could you email it to april@mozilla.com? Thanks!

**Comment by storrgie** [comment]
You should see an email from me shortly, thanks for looking into this.

**Comment by april** [comment]
Hey, @storrgie. Just checking to see if my suggestion worked for you.  :)

**Comment by storrgie** [comment]
Yep!

For posterity it boils down to forcing  `ssl_ecdh_curve X25519;` isn't a good idea due to the current state of the observatory scanners.

**Comment by april** [comment]
More the internet in general, since X25519 only covers like 80% of users.  :)

FYI to anyone who looks at the bug, the fix was changing it to this:
`ssl_ecdh_curve X25519:secp384r1:prime256v1;`
