### ISSUE TITLE
Letter grades should be clickable

### ISSUE THREAD

**Issue by bifurcation** [mozilla/http-observatory-website#19]
On the home page, it would be nice if the user could click the letter grades (or the  corresponding numbers) and see a list of sites with that grade.

**Comment by marumari** [comment]
Ooo, that's a really good idea.  It's exposed in the API, would just need to craft a webpage around it.  Let me think about how to best do this and get back to you.

Have a great weekend!  :D

**Comment by marumari** [comment]
The tricky part will be finding a way to do this while also censoring out any naughty sites, especially given there are no comprehensive lists of these outside of what appears on the top million sites.

If you have any thoughts on how to handle this, it would probably go a long ways towards making this possible.  Thanks, sir!

**Comment by marumari** [comment]
Going to close this because of the concerns above.
