### ISSUE TITLE
Bug in cookie parser?

### ISSUE THREAD

**Issue by Clodo76** [mozilla/http-observatory-website#196]
An example cookie set with response header
`set-cookie: referred_by=0; expires=Sun, 30-Jun-2019 07:35:31 GMT; Max-Age=2592000; path=/; secure; HttpOnly`

Observatory report
`Expires: October 16, 1567 6:00 PM`

**Comment by floatingatoll** [comment]
Should the expires date be “30 Jun 2019”? The spec seems to use white
space, and doesn’t appear tolerant of hyphens.

**Comment by floatingatoll** [comment]
Looks like RFC 850 lets you use hyphens, but mandates you spell out the
full day name. The date header shown doesn’t match any of the three formats
here, anyways - you’re mixing IMF-fixdate “Sun,” and RFC 850 “30-Jun-2019”.

https://tools.ietf.org/html/rfc7231#section-7.1.1.1

**Comment by april** [comment]
This is using the Python `cookiejar` library, which is reasonably strict on correctness and seems to be correct here.  :)
