### ISSUE TITLE
sort hall of fame/shame by alexa rank

### ISSUE THREAD

**Issue by jvehent** [mozilla/http-observatory-website#2]
The popularity of a website is an important criteria in the risk calculation. It would make the hall of fame/shame more meaningful if popular websites were listed at the top.

**Comment by marumari** [comment]
That's a good idea, but surprisingly complicated to do.  Right now, the Hall of Fame/Shame is simply the most recent failing/aced tests.  I could probably right up some kind of materialized view, and add the alexa rank to the site column and then sort by that.

Also, I think people like seeing their site in the "hall of fame", even if it's for a brief period.  Will it be boring seeing the same ten sites in the Hall all the time?

**Comment by jvehent** [comment]
Maybe export a badge with the score that people can put and their sites and links to the http observatory evaluation page?

**Comment by marumari** [comment]
We're going to rework the hall of fame or something, so I'm closing this.  Thanks, @jvehent.
