### ISSUE TITLE
False positives in CSP analysis?

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/http-observatory-website#202]
A site I scanned just now (https://balrog-admin-static-stage.stage.mozaws.net/) has the following CSP:
``` Content-Security-Policy: default-src 'none'; script-src 'self'; img-src 'self' https://.gravatar.com https://.githubusercontent.com https://i1.wp.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src https://admin-stage.balrog.nonprod.cloudops.mozgcp.net/ https://auth.mozilla.auth0.com; frame-src https://auth.mozilla.auth0.com```

The CSP analysis calls out the following things as failures, which don't match my read of the CSP:
* Blocks execution of inline JavaScript by not allowing 'unsafe-inline' inside script-src
* Deny by default, using default-src 'none'

(There's also some additional failures, which I'm guessing are only there because it doesn't believe default-src is 'none'.)

**Comment by floatingatoll** [comment]
The HTTP header value being transmitted by the site seems broken. The extra `content-security-policy: ` would, among other things, likely prevent the default-src from being parsed.

```
$ curl -D https://...
...
content-security-policy: Content-Security-Policy: default-src 'none'; script-src 'self'; img-src 'self' https://.gravatar.com https://.githubusercontent.com https://i1.wp.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src https://admin-stage.balrog.nonprod.cloudops.mozgcp.net/ https://auth.mozilla.auth0.com; frame-src https://auth.mozilla.auth0.com
...
```

**Comment by floatingatoll** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/92684/63282797-7b243780-c264-11e9-8533-6095cd0eb2c2.png">

**Comment by mozbhearsum** [comment]
d'oh

**Comment by floatingatoll** [comment]
@april If you want to add a CSP Analysis table entry "CSP syntax errors were encountered", it might be useful for notifying about this sort of event.
