### ISSUE TITLE
Misidentified as old Symantec cert

### ISSUE THREAD

**Issue by BryanQuigley** [mozilla/http-observatory-website#203]
The following sites show a Symantec warning:
https://observatory.mozilla.org/analyze/elizabethwarren.com
https://observatory.mozilla.org/analyze/amyklobuchar.com

Error: "This site uses a Symantec cert issued on or after June 1, 2016, and will be distrusted by Firefox 63 and Chrome 70 Please replace its certificate immediately."

I can't figure out why it reports that.  The certs aren't old nor are the ones I can see from Symantec.

**Comment by BryanQuigley** [comment]
I tried to dig down into how it's thinking it Symantec, but haven't had luck so far.

Do we need to special case Symantec anymore?  Wouldn't the certs now not be trusted by whatever chain observatory uses?  Can we fully remove this code?

**Comment by april** [comment]
This should now be fixed. I'm not sure what's wrong with the TLS Observatory, but it's long past the time where it's necessary to show on the website.
