### ISSUE TITLE
Observatory stucks at LOADING RESULTS 

### ISSUE THREAD

**Issue by speciale** [mozilla/http-observatory-website#209]
When I try to scan mi site, since yesterday (was working before, with the same site).
I stuck at "Loading results", "Scan in progress" and once I had
Error: speciale.cf is on temporary cooldown. I'm gonna wait

I have this message too in the console

TypeError: r is undefined
9c8a3c92a9778f5d244e.index.js:89:48663

It's working fine in other sites, so the problem is with speciale[DOT]cf

Thanks in advance

**Comment by tkssharma** [comment]
same with me 
`Loading Results`

**Comment by april** [comment]
This was fixed a little while ago.  :)
