### ISSUE TITLE
Observatory may show incorrect HSTS information

### ISSUE THREAD

**Issue by jiggyfiz** [mozilla/http-observatory-website#210]
Hi,

I have been working on improving a couple websites, but it may be Observatory might show incorrect/cached results even though I have forced a rescan.

What is configured (and shown in https://securityheaders.com):

_Strict-Transport-Security | max-age=63072000; includeSubDomains; preload_

With curl, I get the header as it should be:

_< Strict-Transport-Security: max-age=63072000; includeSubDomains; preload_

https://hstspreload.org/ verifies that the domain is preloaded as are the subdomains and header continues to meet the requirements.

Thanks in advance for any reply you may have!

[This](https://observatory.mozilla.org/analyze/wedding.justninja.com) is the site in question.

**Comment by floatingatoll** [comment]
The HSTS preload list used by the Observatory is updated occasionally, but
not on a day-to-day basis, so the Observatory might not yet reflect that
your site is on the preload list.

**Comment by jiggyfiz** [comment]
In other words; it's just me being impatient :) Thanks in any case for the reply!

**Comment by floatingatoll** [comment]
No worries, I think every other check is realtime so you're not wrong to
wonder!
