### ISSUE TITLE
For ECDSA certs, include RSA equivalent size

### ISSUE THREAD

**Issue by april** [mozilla/http-observatory-website#22]
Instead of saying 384-bits, add something like (equiv. RSA 7000000), or whatever it is.

**Comment by BenBE** [comment]
Suggest is to use: https://github.com/BenBE/ssltest/blob/9b6057c880124ef07a4398b38830868104ecd7c5/static/js/rater.js#L1-L41

This rates the strength based on an equivalently strong symmetric cipher using the information found on https://www.keylength.com/ and some interpolation.

**Comment by april** [comment]
Think I'm going to close this one as WONTFIX – I'll note that SSL Labs stopped doing this, presumably because the "RSA equivalent" isn't really exact, and it depends of the curve and a bunch of other things.
