### ISSUE TITLE
wrong HSTS max-age shown

### ISSUE THREAD

**Issue by 532910** [mozilla/http-observatory-website#221]
```
% curl -s -I https://outerface.net | grep strict-transport-security 
strict-transport-security: max-age=63072000; includeSubDomains; preload
```
![image](https://user-images.githubusercontent.com/14617699/83316495-c1181e00-a22e-11ea-8cab-7572a38eac78.png)

**Comment by floatingatoll** [comment]
The age shown is the minimum to earn that score, not the actual age
returned.

**Comment by 532910** [comment]
Hm, OK.

Possibly it will be better to show something like:
`HTTP Strict Transport Security (HSTS) header max-age set to <CURRENT VALUE>. (minimum requirement is six months [15768000 sec])`

**Comment by floatingatoll** [comment]
It does currently say “to a minimum of six months (15768000)”, and those
strings can’t contain values from the HTTP headers (they’re static
strings), so I’m not sure if this can be improved further along those lines.

**Comment by 532910** [comment]
OK ):
