### ISSUE TITLE
Observatory accessible via unsecure domain

### ISSUE THREAD

**Issue by nusa-gr1** [mozilla/http-observatory-website#224]
A link from OWASP Secure Headers Project points to https://mozilla.github.io/http-observatory-website/, which then redirects to http://observatory.allizom.org. This redirect should likely be updated to https://observatory.mozilla.org.

See: https://owasp.org/www-project-secure-headers/#div-technical (currently one of the top 5 search results for "secure headers").

Note: running this domain itself in the Observatory yields an "F" rating (screenshot attached).

<img width="500" alt="Screenshot: Observatory rating" src="https://user-images.githubusercontent.com/61146180/83683849-511ae680-a5e6-11ea-88e9-600450e206e6.png">

**Comment by floatingatoll** [comment]
I filed OWASP/www-project-secure-headers#11 to have them repair their links to the Observatory. Thanks for letting us know.

**Comment by floatingatoll** [comment]
They pushed the fix. Thanks!
