### ISSUE TITLE
SSH Observatory broken due to expired certificate

### ISSUE THREAD

**Issue by tomwassenberg** [mozilla/http-observatory-website#228]
The SSH Observatory test seems to be currently broken, showing "Unable to connect".

This seems to be happening because the test makes a request to https://sshscan.rubidus.com, which is currently serving an expired Let's Encrypt certificate.

I don't know if this infrastructure is under Mozilla's control, but the served cert expired on [2020-06-28](https://crt.sh/?id=2645936572) and no newer cert has been issued.

**Comment by jaylinski** [comment]
Can confirm. You should open the issue in https://github.com/mozilla/http-observatory, since this repo is only for the website.

**Comment by tomwassenberg** [comment]
The issue I originally encountered here has been solved, when I checked just now. The cert has been renewed.

For some targets I'm running into a different error now, but that seems related to https://github.com/mozilla/http-observatory-website/issues/220, so I'll close this.
