### ISSUE TITLE
X-XSS Protection refers to cross-site-scripting as "CSS"

### ISSUE THREAD

**Issue by ProdigySim** [mozilla/http-observatory-website#23]
The tooltip next to the X-XSS-Protection result on the Test Results refers to cross-site scripting as CSS. This should probably be XSS since it is used that way in other places on the site.

> X-XSS-Protection protects against reflected cross-site scripting **(CSS)** attacks in IE and Chrome, but has been superseded by Content Security Policy. It can still be used to protect users of older web browsers.

<img width="286" alt="screen shot 2016-08-25 at 1 11 15 pm" src="https://cloud.githubusercontent.com/assets/857937/17984333/7bb6dc56-6ac5-11e6-872f-066c15316e1c.png">

**Comment by marumari** [comment]
Fixed in 7f7fd99d8f728387535b09735d4e55dc0889e8f7, thank you so much for the report!
