### ISSUE TITLE
WAF as a Compensating Control?

### ISSUE THREAD

**Issue by MClearnsNow** [mozilla/http-observatory-website#246]
Hi All,

Can I get someone's take on WAF being a good compensating control for when websites rate lowly on Observatory against the different criteria? It be much appreciated to hear others as it helps to develop my understanding. Thank you!

Let's take Verizon's login portal as an example. https://observatory.mozilla.org/analyze/secure.verizon.com for https://secure.verizon.com/vzauth/UI/Login

P.S. I don't know if they actually use a WAF for their site.
![image](https://user-images.githubusercontent.com/80426470/110699383-cbebe000-81bc-11eb-9b2f-0fde7c17d1cd.png)

**Comment by gene1wood** [comment]
@MClearnsNow actually this isn't a great place for this type of question, this repo is focussed on bugs/issues with the code of the site. Could I ask that you direct this to another general security forum?
