### ISSUE TITLE
TLS Observatory not opening: CSP script-src issue?

### ISSUE THREAD

**Issue by ankon** [mozilla/http-observatory-website#255]
![image](https://user-images.githubusercontent.com/1210641/126763920-efbfe3a6-83f3-4d69-b92d-046dc32bb78f.png)

**Comment by gene1wood** [comment]
I think the scanner may have been having trouble (and the CSP error is unrelated). Would you try it again and see if the problem persists?

**Comment by ankon** [comment]
Missed this, sorry. Just checked, seems to be indeed ok now. Thanks!
