### ISSUE TITLE
Erroneous (?) "Site down" message

### ISSUE THREAD

**Issue by jbrayton** [mozilla/http-observatory-website#26]
I have a web site at: https://www.goldenhillsoftware.com/

When I enter "goldenhillsoftware.com" and click "Scan Me", I get "Error: Site down".

**Comment by edmorley** [comment]
The site appears to be intermittently down:

$ curl -I --connect-timeout 5 http://goldenhillsoftware.com
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 26 Aug 2016 14:50:18 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://goldenhillsoftware.com/
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Strict-Transport-Security: max-age=16070400; includeSubDomains; preload

$ curl -I --connect-timeout 5 https://goldenhillsoftware.com
curl: (7) Failed to connect to goldenhillsoftware.com port 443: Connection timed out

Trying again:

$ curl -I --connect-timeout 5 https://goldenhillsoftware.com
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 26 Aug 2016 14:51:59 GMT
Content-Type: text/html
Content-Length: 3472
Last-Modified: Wed, 24 Aug 2016 15:30:43 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "57bdbda3-d90"
Cache-Control: max-age=3600, public
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Strict-Transport-Security: max-age=16070400; includeSubDomains; preload
Accept-Ranges: bytes

**Comment by jbrayton** [comment]
You're right. I made some configuration changes this morning that inadvertently broke accepting connections via IPv4. It worked via IPv6. Wow. Thank you!

**Comment by marumari** [comment]
Yep, I see it working now.  Thanks, @edmorley.  Closing this one out.
