### ISSUE TITLE
Let's encrypt ECDSA certificate always gives untrusted or invalid certificate error.

### ISSUE THREAD

**Issue by nakoo** [mozilla/http-observatory-website#263]
This issue is only happened when using ECDSA certificate. RSA certificate is fine.

### letsencrypt.org (ECDSA)

![2021-11-17_15-49](https://user-images.githubusercontent.com/4975021/142233980-f383fb2f-aca5-48ec-8e3a-94623478f562.png)

https://observatory.mozilla.org/analyze/letsencrypt.org#tls

https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=188680074

https://search.censys.io/certificates/d353c3ef9e6bfa93d4d8df09ecc625f5d2199014d97727f29b5f3df9524bcfdb

### gentoo.org (RSA)
![2021-11-17_15-50](https://user-images.githubusercontent.com/4975021/142233949-df72d069-9f41-4488-9ce4-d5928418d068.png)

https://observatory.mozilla.org/analyze/gentoo.org#tls

https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=188701410

https://search.censys.io/certificates/099e4d166cae134d10906a9e8a15f4e329fbc320ebba01c5c1a150f7e76a3c86

**Comment by osirisinferi** [comment]
The reason WHY a certificate is untrusted or invalid is paramount. Just outputting an error message like this is useless, especially if it's a false positive!

**Comment by gene1wood** [comment]
Ya, all sites that assess certificates have been dealing with this issue. SSLLabs by Qualys visualizes this. Other commercial services also raise this as an issue despite the fact that it only affects older browsers.

**Comment by Jieiku** [comment]
Yep, now that I understand the reason for the message I can safely disregard it. (Nothing I can do about it on my end)

**Comment by nakoo** [comment]
> Yep, now that I understand the reason for the message I can safely disregard it. (Nothing I can do about it on my end)

You can fix this issue by `--preferred-chain="ISRG Root X1"`. 
This flag will not include DST Root X3 certificate.

![2022-07-13-16:54:51](https://user-images.githubusercontent.com/4975021/178789498-d704eee2-1f9f-46d3-8f23-d94b61326f82.png)
