### ISSUE TITLE
Sites using Un-trusted certificates return "site down" error.

### ISSUE THREAD

**Issue by vtlynch** [mozilla/http-observatory-website#27]
When you attempt to scan a site using an un-trusted SSL certificate, the scanner returns "Error: Site down".

I'm not sure if the intention is to fail if the certificate is un-trusted, if it is, I think a more accurate error message would be helpful.

Examples:

[https://superfish.badssl.com/](https://mozilla.github.io/http-observatory-website/analyze.html?host=superfish.badssl.com)

[https://spi.dod.mil/](https://mozilla.github.io/http-observatory-website/analyze.html?host=spi.dod.mil)

**Comment by marumari** [comment]
Yeah, I've thought about how to possibly fix this, but it's pretty complicated.  I don't know if the requests module, when told to *not* verify TLS, will tell you if a cert is not validated.  Without knowing that information, it's hard to score.

I've thought of a few ways to make it work, but nothing that I'm super satisfied with yet.  It's on the short list of things to fix though.

**Comment by BenBE** [comment]
As I received a report for my site once, but now not I think this is in error.

Also: The test might want to honor external indicators like CAA, DANE and HPKP as can be seen e.g. for https://ssltest.security.fail/

**Comment by fabianfrz** [comment]
@marumari the test can work this way: 

1. Connect with the certificate check disabled.  
2. If it works, try it with the check enabled. If it does not work anymore, the certificate is not signed by a trusted CA, outdated or the name does not match. It is not important why it failed because all of this issues should result in a warning screen or an error message in the client.

**Comment by marumari** [comment]
Fixed with: https://github.com/mozilla/http-observatory/commit/914d635de349c3c16aa33149586615b8fc7e9aed

And deployed:
https://observatory.mozilla.org/analyze.html?host=incomplete-chain.badssl.com

Thanks for reporting this, @vtlynch!
