### ISSUE TITLE
Scan does not run

### ISSUE THREAD

**Issue by rugk** [mozilla/http-observatory-website#270]
I retriggered a scan of https://observatory.mozilla.org/analyze/privatebin.net some hours ago and reloaded the website, but no scan result yet. It is stuck with "Awaiting scanner instance".

Also the TLS scan result it shows seems to be outdated, too, given it claims it uses an invalid (which the linked cert explainer [nice site BTW!] though says expires at 2022-05-16T04:15:18Z, so I am not sure at all) and only TLS v1.2. SSLLabs confirms TLS 1.3 is available however.

So some server stuff seems to go wrong, does not it?

**Comment by gene1wood** [comment]
> I retriggered a scan of https://observatory.mozilla.org/analyze/privatebin.net some hours ago and reloaded the website, but no scan result yet. It is stuck with "Awaiting scanner instance".

Ya it may have been stuck, when I check it now it's working.

> So some server stuff seems to go wrong, does not it?

Ya, looks like the TLS scanner isn't working. Hopefully we'll be able to get it back working at some point.
