### ISSUE TITLE
FAQ links to non-existent site (htbridge.com/ssl)

### ISSUE THREAD

**Issue by dougwaldron** [mozilla/http-observatory-website#273]
The [FAQ](https://observatory.mozilla.org/faq/) links to `www.htbridge.com/ssl/` under the question "What is htbridge.com?" According to [this issue in the observatory repo](https://github.com/mozilla/http-observatory/issues/388), the domain was changed to `immuniweb.com`.

**Comment by Harsh3363** [comment]
Hii @dougwaldron  I can resolve this issue
