### ISSUE TITLE
Take dnssec into account

### ISSUE THREAD

**Issue by lhirlimann** [mozilla/http-observatory-website#30]
If the domain is highjacked taken over the rest doesn't really matter does it ?

**Comment by BenBE** [comment]
If taken over, you'll have a hard time switching certificates for a domain with HSTS+HPKP+CSP implemented properly.

**Comment by marumari** [comment]
I know there are Python libraries that do DNSSEC checks, but I'm probably going to say that I'm not going to add checks for this into the Observatory until the upstream stuff (requests, Python, the Ubuntu resolver) support it transparently. But I don't even think any browsers support DNSSEC, so currently it is dead in the water for the web. As @BenBE said, HPKP is the present and future way of how we're going to be handling this on the web.

I hope that one day we will also have a DNS Observatory that can do this, though.  That would be great!  Closing this for now.  Thanks for reporting it though!

**Comment by nico3333fr** [comment]
I don't know if it would be possible to add it => this tools seems to perform test on DNSSEC : http://dnssec-debugger.verisignlabs.com (ex http://dnssec-debugger.verisignlabs.com/rocssti.net )

**Comment by J0WI** [comment]
+1 for implementing this as third-party test at least.

**Comment by april** [comment]
Does the Verisign Labs thing have an API I can use? I've been refactoring the website to make this integrations easier, but can't really do that without an API that allows CORS.

**Comment by J0WI** [comment]
Verisign Labs doesn't provide an API, but they reference to https://github.com/dnsviz/dnsviz
