### ISSUE TITLE
It detects my page as weak but there is no attack surface

### ISSUE THREAD

**Issue by fabianfrz** [mozilla/http-observatory-website#31]
the page is static (no dynamic content) so there is no XSS or any issue related to frames possible - even without the headers.
However this is hard to detect so you may close this issue if you like.

**Comment by marumari** [comment]
Yeah, unfortunately there's no good way to detect being "plain static content blog" and "dynamically generated content from a database" (or whatever).  So it treats every site as important.  We do talk a bit about this in the FAQ:

https://observatory.mozilla.org/faq.html

But thank you so much for using the Observatory and providing feedback.  I hope it was a helpful learning experience!
