### ISSUE TITLE
Weak symmetric ciphers not reported as such

### ISSUE THREAD

**Issue by BenBE** [mozilla/http-observatory-website#32]
In light of Sweet32, some ciphers like DES, 3DES, RC4 and IDEA should be marked as weak. Essentially all ciphers with a block size smaller than 128 bit (16 Bytes). For RC2 and RC4 see RFC 7465.

**Comment by floatingatoll** [comment]
See also: https://github.com/mozilla/server-side-tls/issues/156

**Comment by marumari** [comment]
I'm going to close this issue, since it's really an issue with the TLS Observatory.  Thanks for reporting it, though!
