### ISSUE TITLE
Cipher list should display numeric cipher IDs

### ISSUE THREAD

**Issue by BenBE** [mozilla/http-observatory-website#33]
To make validation of results comparable across the various namespaces of ciphers used, the table listing the ciphers should indicate the unique low-level cipher id (2/3 bytes) as that ID can be looked up and referred to the cipher meant by it.

**Comment by marumari** [comment]
Thanks for the idea.  I've opened up a bug on the TLS Observatory to add this information to their API.  Once it's done and that unblocks me, I'll look into adding it to the interface.

https://github.com/mozilla/tls-observatory/issues/138

**Comment by marumari** [comment]
Fixed as of e046e4f715c097e914386e478c6fecd8b3e697b0 and deployed.  Thanks for the suggestion!
