### ISSUE TITLE
mobile layout is messed up

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/http-observatory-website#36]
Just cross posting this from https://github.com/webcompat/web-bugs/issues/3076 as I realized I can contribute directly to the project 

**URL**: https://observatory.mozilla.org/
**Browser / Version**: Firefox Mobile 51.0

**Steps to Reproduce**
1) Navigate to: https://observatory.mozilla.org/
2) Pan around the page/ Observe the buttom button/footer

Actual Behavior:
<img src="https://webcompat.com/uploads/2016/8/f48c1eb3-35db-4ac2-9cad-ad4863aa5652.jpg" width="300" height="550" />

<img src="https://webcompat.com/uploads/2016/8/a93ee12e-b44e-4790-9b84-c8d64ab62b98.jpg" width="300" height="550" />

<img src="https://webcompat.com/uploads/2016/8/a516491a-7dcc-450f-9a61-acf5ce61cd12.jpg" width="300" height="550" />

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by XhmikosR** [comment]
I can make a PR later but this should do the job:

```html
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary collapse in" id="c-button-container">
            <div class="panel-heading">
                <button class="btn btn-default btn-block expandy-panel-button" style="white-space: normal;" type="button" data-toggle="collapse" data-target="#c-results-container,#c-button-container" aria-expanded="false" aria-controls="c-results-container">Click to view all recent Observatory scans. Please note that this may contain sites considered offensive to some.</button>
            </div>
        </div>
    </div>
</div>
```

**Comment by XhmikosR** [comment]
Before:

![1-before](https://cloud.githubusercontent.com/assets/349621/18051628/607cf376-6dfe-11e6-8938-7b4568c826b1.png)

After:

![2-after](https://cloud.githubusercontent.com/assets/349621/18051630/656cb16e-6dfe-11e6-888f-04935f6f4ebb.png)

**Comment by ioana-chiorean** [comment]
🎉 !

**Comment by marumari** [comment]
@XhmikosR: If you can send a PR in on this, I would super appreciate it.  TBH, this is really my first serious webdev project.  So a lot of these issues are a reflection of my severe knowledge deficits when it comes to web design.  😭
