### ISSUE TITLE
Configuration bug?

### ISSUE THREAD

**Issue by davidascher** [mozilla/http-observatory-website#4]
I got to the site via the URL: https://mozilla.github.io/http-observatory-website/

but when I try to submit a domain I end up with a github-served 404 (I was trying to get a scan for thimble.mozilla.org)

**Comment by marumari** [comment]
Yep, that's because it's not yet implemented (as the box says).  In the interim, you can use the cli;

https://github.com/mozilla/http-observatory-cli

Now that I'm back from maternity leave, my hope is to get this working over the next month or so!
