### ISSUE TITLE
Move Google Font to the HTML

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/http-observatory-website#43]
Currently, due to the way Bootswatch themes ship, it's included via an `@import` which doesn't allow the browser to start fetching the Google font until it has fetched the CSS.

Or even better, get rid of it and use system fonts :)

**Comment by XhmikosR** [comment]
Or even better, get rid of it and use system fonts :)

**Comment by FlorentATo** [comment]
Or even better, download the font and load it locally via `@font-face`.
This approach will avoid putting "holes" (i.e. third-party dependencies) in you CSP rules.

Is using Google Font as a fallback relevant ?

**Comment by XhmikosR** [comment]
Your suggestion cannot be better than using system fonts.

**Comment by FlorentATo** [comment]
True, but that's the closest we can get without breaking bootstrap's UI.
That being said, having fancy font to render might not be @marumari top priority :)

**Comment by marumari** [comment]
I recognize that this is a problem, but I think I'm go to leave it unfixed. The rationale is that I'm simply using a bootswatch theme and I don't want to be dealing with monkey-patching it every time there is a revision.  Sorry, but thanks for bringing it to my attention!
