### ISSUE TITLE
Add favicons

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/http-observatory-website#44]
Someone who's good with designing should make a logo we can use to generate the various favicons.

**Comment by marumari** [comment]
Totally!  I am not a designer, but hopefully we will get something soon.  Thanks for filing the bug!

**Comment by marumari** [comment]
@supnah, how hard would it be to get a favicon created that represents the Observatory?

**Comment by supnah** [comment]
The easiest and proper brand thing to do here would be to use the same favicon used on the rest of the .org, as can be seen here: https://www.mozilla.org/en-US/?v=b

There may be more options or a system for this after more work on the brand is done, but for the time being using anything else wouldn't make sense. Work for you?

**Comment by supnah** [comment]
To @XhmikosR's point, we would prefer not to brand observatory with its own logo. For more on this you can check out the reasoning here: https://wiki.mozilla.org/Engagement/Brand/Guidelines_and_Resources

**Comment by XhmikosR** [comment]
I only suggested this because I wanted something to show up. It's your call what to use.

**Comment by supnah** [comment]
No worries - just wanted to provide the rationale in case it was helpful. Thanks!

**Comment by marumari** [comment]
Sounds good to me.  I'll use Mozilla's favicons.  :)
