### ISSUE TITLE
Scans that return "site down" should force rescans on the next scan

### ISSUE THREAD

**Issue by kkretsch** [mozilla/http-observatory-website#45]
I always get an error "Site down" and see no access at all in the nginx logs.
Website is configured on 80/443 as http and https so it should reply to any request. But none is coming to the server it seems.
Is that a matter of using a newer TLD? If s/o please could try for https://vocab.guru/ ?

**Comment by edmorley** [comment]
I'm not sure what is causing this issue (I'm not involved with this project), but as a side note the blog subdomain (that the one above redirects to), has an incomplete certificate chain:
https://www.ssllabs.com/ssltest/analyze.html?d=blog.vocab.guru&s=78.47.173.78

**Comment by kkretsch** [comment]
Thanks @edmorley , I just corrected that I hope. Glitched through my hands last evening.

But that should not be the problem with the main site running on a different server.

**Comment by marumari** [comment]
I think what happened is that the site was down when the initial scan was done.  Since it caches results for 24 hours (unless you force a rescan), it continues to say that the site is down.

**Comment by w0ts0n** [comment]
+1 same issue here. 
Setup a new site, ran a scan before DNS had propagated and got "site down" then ran into the above issue.

**Comment by avacariu** [comment]
As a workaround until this is fixed, you can trigger a rescan by running `submitScanForAnalysisXHR('example.com', function(){}, function(){}, 'POST', true, true);` in the console.

**Comment by marumari** [comment]
A third alternative is using the cli (pip install httpobs-cli) and running httpobs -r example.com.  :)
