### ISSUE TITLE
Site needs a lot of work to look good on mobile devices

### ISSUE THREAD

**Issue by april** [mozilla/http-observatory-website#47]
Much thanks to @XhmikosR for his work on #46, which greatly improved the front page.

The results page is a lot more complicated though, and needs a _lot_ of work.  If there's a designer out there that is great at this stuff, I'd really appreciate the help.

**Comment by XhmikosR** [comment]
I don't think it needs a lot of work. A few tweaks and should be fine on
mobile too. That's the idea behind using frameworks :)

**Comment by k-nut** [comment]
One of the biggest problems seems to be that the tables are too wide and by that break the layout. 

One possible workaround would be to wrap the tables in a bootstrap `table-responsive` div which sets their `overflow-y` to `scroll` leading to the tables cutting of at the border of their container but becoming scrollable. [Documentation](http://getbootstrap.com/css/#tables-responsive)

Would you like to see this in a pull request?

**Comment by april** [comment]
If you can make it all work and look decent on mobiles I would love a PR . :)

**Comment by thetronjohnson** [comment]
Can I work on this?

**Comment by april** [comment]
Yes please. I will say that one of my plans over the next month is to convert everything to using webpack and ES6 and Bootstrap 4 over the next month, so please keep that in mind.  :)

**Comment by thetronjohnson** [comment]
I'm a beginner, but I'll do my best

**Comment by april** [comment]
Actually now that I think about it, would you be okay with holding off for a couple weeks? I can (at the very least) move things to webpack, which should make your life a lot easier.  :)

**Comment by thetronjohnson** [comment]
okay

**Comment by april** [comment]
I guess six weeks (and 2.5 years) is a lot longer than a couple weeks, but the website should now be fully responsive. Please let me know if you run into any issues.

Thanks!
