### ISSUE TITLE
Access-Control-Allow-Origin: null ---> -50 ???

### ISSUE THREAD

**Issue by hdatma** [mozilla/http-observatory-website#5]
The string "null" is perfectly legal, and in fact advisable if you are a hosting domains and want to 
enforce the protection above local overrides. 

Ref. http://www.w3.org/TR/access-control/#access-control-allow-origin-response-header
In practice the origin-list-or-null production is more constrained. Rather than allowing a space-separated list of origins, it is either a single origin or the string "null".

**Comment by marumari** [comment]
Hmm, that definitely shouldn't be getting a -50.  Can you provide the site name that you got this result with, and I'll take a look?  Thanks!

**Comment by marumari** [comment]
@hdatma: ping on a site that you're having the issue with?  Or I can create one, but it'll be a lot easier to test on an existing site.  Thanks!

**Comment by hdatma** [comment]
The grade is silly. 
No need for tests.
