### ISSUE TITLE
Enforce LF for the repo

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/http-observatory-website#50]
On Windows I end up with different hashes due to line endings being different.

So using LF will make the behavior consistent.

**Comment by marumari** [comment]
This shouldn't be too hard to do, would just need to update render.py to do line ending conversations after it copies files to the destination directory.

**Comment by XhmikosR** [comment]
No idea about that but I was talking about the git repository endings. I'll
make a PR when I'm at home.
