### ISSUE TITLE
Error when domain exists but no site

### ISSUE THREAD

**Issue by davebremer** [mozilla/http-observatory-website#52]
If the domain is registered but no website exists the message is "Error: name.example is an invalid hostname". I tried this on one with just mx records. This is technically correct. I thought it said "invalid domain" yesterday which wasn't right.

I read the error as implying the name isn't correct - it is registered and in use, just not for web access.

This might be beyond the intended scope - reporting dns  sanity checks would be useful. There's other tools that do that though. You could deep link the searched domain as a "check on xxx" or roll your own. See http://www.dnsstuff.com/tools#dnsReport%7Ctype=domain&&value=NAME.EXAMPLE or http://mxtoolbox.com/SuperTool.aspx?action=a%3aNAME.EXAMPLE&run=toolpage#

**Comment by marumari** [comment]
Can you give me an example domain that I can test with please?  Thanks much!

**Comment by floatingatoll** [comment]
_dmarc.mozilla.com is one such domain.

**Comment by davebremer** [comment]
Hi April
Mine is Bremer.nz<http://bremer.nz> I just use it for email - using zoho  for that. Registered via iwantmyname.com<http://iwantmyname.com>

The example sites would be
http://www.dnsstuff.com/tools#dnsReport%7Ctype=domain&&value=Bremer.nz

http://mxtoolbox.com/SuperTool.aspx?action=a%3aBremer.nz#

This might take you down a rabbit hole of dns. Possibly worthwhile, and also possibly out of scope for current work.

Clarifying that the domain exists/registered but has no web server might be an option to consider.

Cheers
Dave

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Aug 30, 2016 at 7:42 AM +1200, "April King" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you give me an example domain that I can test with please? Thanks much!

-

**Comment by marumari** [comment]
I think in this case the Observatory's message is right: it's a hostname that exists, but it's invalid for scanning because it contains no A record. It's such an edge case that I think it's not worth the effort.  I appreciate the bug report, though.  Thank you!
