### ISSUE TITLE
HSTS preload call is case-sensitive

### ISSUE THREAD

**Issue by FlorentATo** [mozilla/http-observatory-website#59]
Consider https://hstspreload.appspot.com/?domain=example.com is part of the HSTS preload list.

Trying https://hstspreload.appspot.com/?domain=Example.com (uppercase "e") will return `Initial redirect is to an insecure page.`

Note: According to my tests, https://hstspreload.appspot.com seems to always convert addresses to lowercase.

**Comment by marumari** [comment]
I'll convert it to lower upon making the call, but would you be willing to open up a bug on their repo:

https://github.com/chromium/hstspreload

Thanks!

**Comment by marumari** [comment]
https://github.com/chromium/hstspreload.appspot.com/issues/60

**Comment by marumari** [comment]
Should be fixed and live now:
https://observatory.mozilla.org/analyze.html?host=Pokeinthe.io
