### ISSUE TITLE
Rename /HTTP Observatory/

### ISSUE THREAD

**Issue by karlcow** [mozilla/http-observatory-website#6]
This is not really in the present state an HTTP observatory, but more a useful tool to test HTTPS.

I would be in favor of renaming it

s/HTTP Observatory/HTTPS Observatory/

And probably with a subline giving the scope on security.

PageSpeed is a lot closer of what is an HTTP observatory 
https://developers.google.com/speed/pagespeed/

Redbot.org is also good at giving advice on the sanity of HTTP headers.
https://redbot.org/

**Comment by marumari** [comment]
There is nothing in the HTTP Observatory that tests HTTPS, other than some tests will pass or fail based on whether or not you have HTTPS enabled.  For example, you can't enable HSTS (an HTTP header) without HTTPS.

CSP, XFO, XXSSP, XCTO, CORS, HSTS, HPKP, Cookies: these are all tests of HTTP headers
Redirection: a test of HTTP behavior to redirect to the HTTPS version of the site
SRI, CORS, contribute.json: Test to see if your content is implemented using modern security methods

Nothing to do with HTTPS.

**Comment by marumari** [comment]
Here is an example of it testing a site with no HTTPS at all:

https://mozilla.github.io/http-observatory-website/analyze.html?host=http.badssl.com

**Comment by karlcow** [comment]
Understood what you are saying, but it assumes that a site which doesn't provide HTTPS is a bad site. Let's take for example. https://mozilla.github.io/http-observatory-website/analyze.html?host=otsukare.info

HTTPS is not something which is mandatory. But that might be the point you want to make, aka push people to switch to HTTPS. Then it's another type of statement (I disagree with). :) In this case there is no solution, and you can close peacefully this issue.

**Comment by marumari** [comment]
Well, you can implement all the proactive controls you want (CSP, SRI, etc.), but without HTTPS they can be easily stripped away, leaving you with no security at all.  So that's why it's impossible to pass without having HTTPS enabled.  :)

**Comment by karlcow** [comment]
Yes agreed, but it doesn't mean you need them. A site which is sending information doesn't necessary require all of these if you do not have cookies, comments, etc. I guess it's then a separate issue in how the score is established and what are the preliminary requirements which requires HTTPS.

**Comment by marumari** [comment]
But that's not true either, unfortunately.  For example, the DDoS attacks on GitHub:

http://arstechnica.com/security/2015/04/ddos-attacks-that-crippled-github-linked-to-great-firewall-of-china/

Was because people were visiting http pages and malicious JavaScript that attacked GitHub was being injected.  Even if your site doesn't have any non-sensitive data, not having HTTPS allows your visitors to be turned into weapons.  :(
