### ISSUE TITLE
Server are reported as down, but it is alive.

### ISSUE THREAD

**Issue by tuxmaster** [mozilla/http-observatory-website#63]
There test server are reported as down, but it is alive.
Other site's can scan it without any problems.
How does the detection algorithms work?

**Comment by marumari** [comment]
What site?  If you go to the front page and force a rescan, does that fix things?

**Comment by tuxmaster** [comment]
No this will not fix it.
For example:  familie-büttner.de/xn--familie-bttner-osb.de

**Comment by marumari** [comment]
Oh, I see.  This is actually a duplicate of bug #27.  If you fix the bad cert on your site, it should start working fine.
