### ISSUE TITLE
no direction for deploying the website

### ISSUE THREAD

**Issue by moustafak** [mozilla/http-observatory-website#65]
would love to see directions for deploying the website.. is there a plan to produce this?

**Comment by marumari** [comment]
Good point, I'll add that.  You should just be able to clone the gh-pages branch and get the whole site as it appears in real life.  Super easy!

**Comment by moustafak** [comment]
when loading the pages they it doesn't seem to render: see https://snag.gy/4npmjY.jpg

I am still not 100% sure but i think this uses jinja2 and i have now installed through pip but that's where things got out of my depth and really need instructions

**Comment by marumari** [comment]
You're using the templates directory.  You either need to use the gh-pages branch:

git clone -b gh-pages <url>

Or you need to use what is in the dist directory.  :)

**Comment by moustafak** [comment]
yes, thank you! that works as expected now. please add to the readme :+1: 

I originally thought the web component would work with the local scanner. I don't suppose the web component can be made to allow local ip's and read json output produced by the local scanner easily?

**Comment by marumari** [comment]
There should just be a single line to change to point it to a different scanner.  I'll make sure I add that information to the documentation.

**Comment by briner** [comment]
For your information, I did deployed and [documented](https://github.com/briner/tech-notes/blob/master/observatory_by_mozilla.md) it for Debian Jessie

**Comment by linickx** [comment]
I think the instructions need updating? 

```
$ git clone -b gh-pages https://github.com/mozilla/http-observatory-website.git moz-web
Cloning into 'moz-web'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 3242 (delta 40), reused 74 (delta 30), pack-reused 3150
Receiving objects: 100% (3242/3242), 2.40 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (2250/2250), done.
$ cd moz-web/
$ find ./ -name httpobs.js
$ find ./ -name httpobs-third-party.js
mbp:moz-web $ 
```

The files to update are not found, and the directory structure looks different now to what @briner did. I'm not sure how to add the website to my [docker-compose](https://github.com/linickx/mozob) that brings up both TLS & HTTP Observatories. Please can you help?

**Comment by linickx** [comment]
... never mind, [figured out ](https://github.com/linickx/mozob/blob/master/website/Dockerfile)how to do it with node :)
