### ISSUE TITLE
Unsupported ciphers?

### ISSUE THREAD

**Issue by Seegras** [mozilla/http-observatory-website#66]
I've got a very small set of ciphers that I allow: 
https://www.ssllabs.com/ssltest/analyze.html?d=seegras.discordia.ch&s=2a05%3afc84%3ac%3a0%3a0%3a0%3a0%3a8&latest

Now the observatory thinks the site is not available via TLS. Either you don't support any of these ciphers, or there is an issue with IPv6 (since it uses an IPv6-Address on its own) or SNI (needs SNI for IPv4).

**Comment by marumari** [comment]
That's an unusual combination of ciphers, but it should work.  Can you open up a bug about this on the repository of the software we use for TLS scanning?  The bug would be in there:

https://github.com/mozilla/tls-observatory/issues

Thank you so much!

**Comment by marumari** [comment]
Looks like whatever bug was causing this issue was fixed in the TLS Observatory, so I'm going to go ahead and close this.  :)
