### ISSUE TITLE
obsovatory says "Content Security Policy (CSP) header not implemented", but it is provided

### ISSUE THREAD

**Issue by gustafn** [mozilla/http-observatory-website#67]
CSP is correctly accepted and parsed by browsers (e.g. Chrome), but the web-tool says that it is no implemented. Also the X-XSS protection is not accepted. Can it be that there is a problem with the request header parser in observatory? Here are the headers as seen from a browser. 
```
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 5945
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.ckeditor.com code.jquery.com ajax.googleapis.com; img-src 'self' cdn.ckeditor.com ipv6-test.com; style-src 'self' 'unsafe-inline' cdn.ckeditor.com;
Content-Type: text/html; charset=utf-8
Date: Mon, 05 Sep 2016 09:06:59 GMT
Expires: Mon, 05 Sep 2016 09:06:59 GMT
Pragma: no-cache
Server: NaviServer/4.99.12
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

```
The website is openacs.org (the CSP will be made much less liberal in the near future).

**Comment by marumari** [comment]
Hmm, very strange.  When I look at the raw headers (on the website), I don't see any of those things.  Do you have some kind of intermediary that might be blocking the Observatory?

**Comment by gustafn** [comment]
sigh, wrong alarm: no blocking, but IPv4 vs. IPv6. Many thanks for the quick response!
