### ISSUE TITLE
securityheaders.io third party scan fails without HTTP

### ISSUE THREAD

**Issue by tdelmas** [mozilla/http-observatory-website#69]
When you ask to scan "https://example.com", it scan "example.com" with securityheaders.io, and securityheaders.io failed because there is no http. (But if you scan "https://example.com" with securityheaders.io it works)

**Comment by marumari** [comment]
I could possibly fix this on my end, but it's probably better fixed by the site owner.

@ScottHelme, could you take a look at this one please?  Thanks!

**Comment by ScottHelme** [comment]
I found the problem: 

https://github.com/mozilla/http-observatory-website/blob/b3b916132f5d00732563c4773c0edfc28e17585d/dist/js/httpobs-third-party-1.0.7.js#L274

You're not passing me the scheme in the request to securityheaders.io which is where it's failing. I need you to pass me the scheme on all requests, something like:

    var API_URL = 'https://securityheaders.io/?followRedirects=on&hide=on&q=' + Observatory.scheme + Observatory.hostname;

I had a look at the code but I can't see where to add it :-)

**Comment by tdelmas** [comment]
An url to test it : https://observatory.mozilla.org/analyze.html?host=tdelmas.ovh

**Comment by marumari** [comment]
Any chance I could convince you to test both simultaneously, and choose https if they both work?

**Comment by tdelmas** [comment]
Now it's fully broken, not just the securityheaders.io test :)

**Comment by marumari** [comment]
Hah!  Derp!

**Comment by marumari** [comment]
Should be fixed now.  I am real good at this computer thing.  Or something.

**Comment by marumari** [comment]
That is to say, the site itself should be working for tdelmas.ovh now.  The actual issue itself remains unfixed.

**Comment by tdelmas** [comment]
I confirm, thanks!
