### ISSUE TITLE
CSP header parsing error with multiline definition

### ISSUE THREAD

**Issue by ajarope** [mozilla/http-observatory-website#70]
Snippet from Apache config follows.

Header always set Content-Security-Policy \
        " \
        default-src 'self'; \
        style-src 'self' \
                'unsafe-inline' \
                'sha256-e7cmLP/1kNNvlmAL6WpxAbxYm11otS+g2JqtWfJjyJ4=' \
                'sha256-jE00AJAJfF4e5zCe/WZdF7CzTFqwV0hYFN1ICf2NT88=' \
                'sha256-0+eUWXEzIzayXtwbs4qgGqcUroB222vieZ1QP7fQ6so=' \
    'sha256-H+MZMHAjxtX51BD5NQvR2VBEYdZkra7aCuCgN0suCfk=' \
                'sha256-S7jkx8JtJicm/79wzDgSPAz8c2i1ns8O8hI/DpuWN88='; \
        script-src 'self' 'unsafe-inline' https://cdn.ampproject.org/v0.js https://cdn.ampproject.org/v0/validator.js; \
        upgrade-insecure-requests; \
        base-uri 'none'; \
        frame-ancestors 'none'; \
        sandbox allow-same-origin allow-scripts;\
        "

**Comment by marumari** [comment]
Fixed in https://github.com/mozilla/http-observatory/pull/145. Thanks for reporting this!
