### ISSUE TITLE
Compatibility Level Intermediate but is Modern

### ISSUE THREAD

**Issue by Fleshgrinder** [mozilla/http-observatory-website#72]
https://observatory.mozilla.org/analyze.html?host=movlib.org#tlsobservatory

The compatibility level is reported as being intermediate but it actually is modern. There is absolutely no reason given how it comes to that conclusion. Here the relevant parts from the nginx configuration but it can be verified by the other checks as well:

```
ssl_ciphers                ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
ssl_ecdh_curve             prime256v1;
ssl_prefer_server_ciphers  on;
ssl_protocols              TLSv1.2;

add_header  Strict-Transport-Security 'max-age=63072000; includeSubDomains; preload' always;
```

I would guess that it is because I set the HSTS max. age to 63072000 and not 15768000 as recommended, however, the 63072000 is what Google recommends and actually better.

**Comment by floatingatoll** [comment]
Does lowering the HSTS max age to 15768000 make it report modern rather
than intermediate, if you lower it temporarily for testing purposes?

**Comment by marumari** [comment]
Not related to HSTS; the Mozilla Modern requirements require ECDSA certs and you're using an RSA cert.  :)

**Comment by Fleshgrinder** [comment]
I understand, thanks for the info. I still do not consider this issue resolved because in the Wiki it is stated:

> RSA key size: 2048 (if not ecdsa)
>
> — MozillaWiki: [Security/Server Side TLS: **Modern** compatibility](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility)

Which is clearly met. Even if ECDSA is a hard requirement – which is not clear judging from the Wiki – reporting intermediate is still not quite right. Maybe a Modern Minus or Almost Modern or Intermediate Plus or … I really don't know. The fact that the output is completely silent about the reasons a particular compatibility level was chosen is simply not really helpful. Not every user is as annoying as I am and drops an issue here. 😉
