### ISSUE TITLE
Scan website without http (and HSTS preload)

### ISSUE THREAD

**Issue by tdelmas** [mozilla/http-observatory-website#74]
When scanning a website only responding with https:

> hstspreload.appspot.com✓
> Host: 	example.com
> Preloaded: 	Yes
> Notes: 	This site's HSTS header does not meet current preloading requirements.
> Note that some of the current requirements did not apply to domains preloaded before February 29, 2016.
> Complete Results: 	https://hstspreload.appspot.com/?domain=example.com

But the HSTS preload API answer contains only one warning with:
> code:"redirects.http.does_not_exist"
> summary:"Unavailable over HTTP"
> message:"The site appears to be unavailable over plain HTTP (http://tdelmas.eu). This can prevent users without a freshly updated modern browser from connecting to the site when they type/follow a URL with the http:// scheme (or with an unspecified scheme). However, this is okay if the site does not wish to support those users."

**Comment by marumari** [comment]
Thanks for letting me know!  This was a recent change, so I'll get it fixed soon. CC'ing @lgarron just so that he's aware.  :)

**Comment by lgarron** [comment]
I presume this is due to caching on your end?

**Comment by marumari** [comment]
I don't do any caching with your site, so it's probably just misinterpreting the results.  :)

**Comment by marumari** [comment]
Looks like the API is working properly, so it's almost certainly on my end.  :)

**Comment by marumari** [comment]
This was fixed during the Great Refactoring of 2016: 7e0b5a25dc525ae5e8380b2db67ed89d0f8b718c

Lemme know if you run into any more issues!
