### ISSUE TITLE
Referrer Policy in document vs. HTTP header

### ISSUE THREAD

**Issue by jacobbednarz** [mozilla/http-observatory-website#75]
Hi there! 👋 

I've ran our application through the Mozilla Observatory and noticed that using a referrer policy within the document isn't picked up and it is only looking for the HTTP header value. Is this intended behaviour? Are there any benefits of using one over the other? Very interested to hear from anyone on this subject as I can't find anything too well documented on the differences along with pros/cons of each.

Thanks in advance!

**Comment by marumari** [comment]
It is in fact totally fine, it's just that I haven't had a chance to write the code for it yet.  CSP has the same problem:

https://github.com/mozilla/http-observatory/issues/105

I have gone ahead and added RP to the bug, since they're very overlapping bugs.

**Comment by jacobbednarz** [comment]
Awesome stuff! Appreciate the information and the service. Many gold stars to you for your efforts ⭐️ ⭐️ ⭐️

**Comment by marumari** [comment]
You're very welcome, and thank you for your attention to improving security for yourself and your users.  I'm going to close this bug, but I'll update the aforementioned bug as I make progress.  It is something I hope to get working over the next month or so.  :)

**Comment by april** [comment]
Hey, @jacobbednarz? Do you have a site I can test your use of <meta> referrer policy?  Thanks!

**Comment by floatingatoll** [comment]
Phonebook should have one set, if you need one under our control.

**Comment by april** [comment]
That's a bit tricky because of the 2FA, I have some easier ideas if OP doesn't have something.

**Comment by jacobbednarz** [comment]
@april Sure! https://themeforest.net will have the referrer policy as the meta tag.
