### ISSUE TITLE
Cannot check fields on small touch screen

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory-website#77]
On the homepage, options such as "Force a rescan instead of returning cached results" do not work.

This is because the help widget opens over the checkbox, and does not toggle the state.

This might be due to how iOS does the hover event.

![img_3471](https://cloud.githubusercontent.com/assets/1296695/21064989/fc02dd2c-be55-11e6-9701-1032c771fc89.PNG)

**Comment by craigfrancis** [comment]
Forgot to add, this probably relates to #47

:-)

**Comment by marumari** [comment]
Yeah, I really suck at this stuff.  I'm not really a web designer, so I'm struggling.  Am going to try to spend more time working on it this upcoming quarter or so!

Thanks for the issue!

**Comment by craigfrancis** [comment]
You're not alone :-) ... it's especially tricky trying to get a lot of information onto a small screen.

I'd be tempted to go with a simple [?] type icon at the end, which can be created as a normal link:

    <label><input type="checkbox" /> Include my site in the public results <a href="/path/to/info"><img src="/path/to/info.gif" alt="More info" /></a></label>

Then you could add some JavaScript to apply an onclick event (so the info can appear as an overlay) - then if the JS fails to load, it still works :-)

This icon then tells users there is more info available, and if they want it, they can click on the icon; whereas clicking on the label continues to toggle the checkbox.

It also helps trying to avoid hover events, as they don't really work on touch screens :-)

You also need to check links inside labels on different browsers, as they can cause problems - normally this is because clicking on the link can toggle the checkbox as well (so you might need an e.preventDefault).

And as a side thing, I've always been told to avoid "Don't" checkboxes, because a ticked box is seen as something positive (I want this), but options that say "Don't" switch that around... that said, it would mean that the 1st and 3rd checkboxes would then need to be ticked by default (maybe changing the order will help?).

**Comment by marumari** [comment]
Fixed in 86355fde223d9331af1472eb80b31f658f631688  :)

**Comment by marumari** [comment]
And I'm still thinking about the "don't" thing.  :)

**Comment by craigfrancis** [comment]
Thanks April :-)
