### ISSUE TITLE
[CSP] hstspreload API moved to hstspreload.org

### ISSUE THREAD

**Issue by spaze** [mozilla/http-observatory-website#78]
HSTS Preload API seems to be moved to hstspreload.org, originally at hstspreload.appspot.com.

CSP is blocking the 3rd party HSTS preload call, because

```
Refused to connect to 'https://hstspreload.org/api/v2/preloadable' because it violates the following Content Security Policy directive: "connect-src https://api.ssllabs.com https://hstspreload.appspot.com https://http-observatory.security.mozilla.org https://securityheaders.io https://tls.imirhil.fr https://tls-observatory.services.mozilla.com https://www.htbridge.com".
```

https://github.com/mozilla/http-observatory-website/blob/7e0b5a25dc525ae5e8380b2db67ed89d0f8b718c/js/httpobs-third-party.js#L170 needs fixing, also CSP header needs to be changed.

Thanks for looking into this!

**Comment by marumari** [comment]
@lgarron!  You're killing me here.  :P

**Comment by marumari** [comment]
Okay, fixed in 6b399473498c29365d4d8398de6c9441156fbdd2 and deployed to the site.  Thanks for letting me know!

**Comment by spaze** [comment]
Thank you @marumari! I can confirm it's okay now, thanks!

**Comment by lgarron** [comment]
> @lgarron! You're killing me here. :P

Nothing like breaking changes on a Friday night, eh?
The redirect is a 302 for now, but I guess that doesn't help with CSP.
