### ISSUE TITLE
inconsistent handling of "can't check" tests

### ISSUE THREAD

**Issue by hwine** [mozilla/http-observatory-website#8]
I have an HTTP only site with only a very simple static page at the root. (dtor [dot] com) Of course, this means a guaranteed 'F', which is fine, but the analysis phrases results of things which can not be tested differently.

The TLS checks are marked as "failed" (agreed), but the sub-resource integrity is marked as 'passed', simply because my root page doesn't have a script tag.

I'm not sure what the "best" solution is here - but the inconsistency did make me have to rescan the results several times to make sure I understood what was being communicated. Maybe a 3rd icon for "can't test" - negative score still allowed?

**Comment by marumari** [comment]
I'm not sure what you mean here.  Subresource integrity doesn't have anything to do with HTTPS; it simply means that if you use <script> tags that they have an integrity attribute locking them to a specific version.  Since you don't include any <script> tags, you can't fail.  Whereas not having HTTPS *is* a failure, as it exposes visitors to your site to any number of man-in-the-middle attacks.

**Comment by hwine** [comment]
Well, I guess that supports my general point about being confused - I can't even explain it well. (I split my original thought into 2 tickets and didn't get this one in order.)

Let me try with a picture and a better example:
![screen shot 2016-07-19 at 15 04 50](https://cloud.githubusercontent.com/assets/132412/16968267/9a39e5bc-4dc2-11e6-9bd1-64110e58ca29.png)

Neither the HPKP header nor the HSTS header can be set without https, yet the first is "pass", and the second "fail". With the strong emphasis on HTTPS, I'd expect both to be marked as "fail". If there's no penalty for lack of HPKP, that's fine.

Subresource integrity & cookie values are really a "can't tell" since none were provided (and the concerns I bring up in #9 also apply). "Pass" feels too strong - I really think this is a tri-valued state.

**Comment by marumari** [comment]
I've struggled with the scoring a lot, in my attempts to make it consistent and reasonable.

The only way you can fail the HPKP test is if the header is invalid.  It's considered optional; you get a bonus if you do implement it (+5), but you don't get penalized if you don't.

Perhaps I could use a different icon for HPKP, to signify that it's optional?

**Comment by hwine** [comment]
/me leaves it to better-ux-designers-than-I to address it. It's more of a "nit" than a bug (assuming #9 changes things the way I think it will), so "close/wontfix" is reasonable.

**Comment by marumari** [comment]
Sounds good!  :)
