### ISSUE TITLE
Search doesn't work when URL contains query string

### ISSUE THREAD

**Issue by bdukes** [mozilla/http-observatory-website#80]
When the URL for this site contains a query string (e.g. observatory.mozilla.org/?utm_source=html5weekly&utm_medium=email), nothing happens when submitting a site to analyze.  The URL is changed to append "analyze.html?host=…" _after_ the existing query string, and so the `host` parameter isn't recognized.

**Comment by marumari** [comment]
Thanks for bringing this to my attention.  It should be fixed in dffe701fd510f9bfe4ffbc47db55989159dee339. Was the Observatory featured in a newsletter or something?

**Comment by bdukes** [comment]
It was mentioned a while ago, and I just not got to it on my list of things to read 😄 Thanks!
