### ISSUE TITLE
<title> for /analyze.html?host=xyz is too generic

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory-website#83]
The <title> tag for /analyze.html?host=xyz is simply "Observatory by Mozilla", which offers no clue as to what the link actually contains. It would be more useful if it said any of:

Observatory by Mozilla: Scan Summary
Observatory by Mozilla: Scan Summary for 'xyz'
Observatory by Mozilla: Scan Summary #3065579

or so on.

**Comment by marumari** [comment]
I'm sure there's some reasonable way to do this in Jinja.  Maybe.  :)

**Comment by marumari** [comment]
All fixed, huzzah!

**Comment by floatingatoll** [comment]
See also #136.
