### ISSUE TITLE
No results loading?

### ISSUE THREAD

**Issue by damienmckenna** [mozilla/http-observatory-website#84]
I've tried scanning a site but the results don't work regardless of whether I use Chrome, Firefox or Safari, even when the browser was left sitting for an hour. Is there something broken at the moment?

**Comment by marumari** [comment]
Yes, redis crashed on our backend and that caused a bunch of scans to hang.  It should be fixed now.  Sorry about the issue!

**Comment by damienmckenna** [comment]
Sweet, it's working now, thank you!
