### ISSUE TITLE
Consider support for a "What to fix next" banner

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/http-observatory-website#86]
After speaking with @marumari we discussed how the rating is somewhat arbitrary, however I suggested that perhaps a solution would be providing a heads up banner on what would be good to implement next.

So this would be based upon difficulty and benefit on the security cheat sheet. So for example if the user didn't have HSTS on their site but did have SSL and redirection to HTTPS already the banner might suggest:
  "Hey the next thing we would advise you to implement would be [HSTS](https://wiki.mozilla.org/Security/Guidelines/Web_Security#HTTP_Strict_Transport_Security) or [look at other suggestions](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Web_Security_Cheat_Sheet)"

The algorithm would always try to pick the easiest thing to implement that has over a low impact. So it would never suggest robots.txt but might suggest SRI if all other 'low' difficulties have been completed.

The idea is to prompt developers to do quick fixes that could have really large impacts, like I think HSTS should be really highlighted as many developers aren't aware of it yet, despite it being just a header once they have a cert.

I don't think we ever link to this great matrix either:
https://wiki.mozilla.org/Security/Guidelines/Web_Security#Web_Security_Cheat_Sheet

**Comment by floatingatoll** [comment]
+1, would be invaluable when doing gradual improvement of a site.

On Tue, Jan 31, 2017 at 1:55 PM, Jonathan Kingston <notifications@github.com

**Comment by edmorley** [comment]
This has now been implemented :-)

**Comment by april** [comment]
Oh hey yeah I totally did that!  :D
