### ISSUE TITLE
Suggestion: a test on robots.txt

### ISSUE THREAD

**Issue by nico3333fr** [mozilla/http-observatory-website#87]
Hi there,

while reading to https://wiki.mozilla.org/Security/Guidelines/Web_Security#robots.txt I'm wondering if Mozilla Observatory could add a test on robots.txt (if present): 

if there are "disallow" instructions in it, just leave a comment like: "Make sure disallow instructions are not used as a way to prevent the disclosure of private information or to hide portions of a website".
I suppose that this test could not add or remove points, however, it could be a good advice.

Thanks for reading, and may the force be with you,
Nicolas

**Comment by floatingatoll** [comment]
[-5] Robots.txt is a widely-ignored standard and creates a false perception
of security.

**Comment by Nightfirecat** [comment]
@flatingatoll It is still useful to prevent excess load on certain sections of websites from crawlers.

I agree that it might be a good idea to add a mention on that.

**Comment by floatingatoll** [comment]
We have blacklisted at least ten crawlers at Mozilla for malicious behavior
after they blatantly ignored robots.txt and all reasonable crawler
principles.

**Comment by nico3333fr** [comment]
Robots.txt disallow is often badly understood: it should used to tell to "honest" robots not to crawl some parts (as @Nightfirecat says, to prevent crawl payload, or non-necessary indexation). However, some people are using it to tell "I've something to hide, don't come here", which is stupid. :)

As it is a standard used and recommended (for example by Opquast = OPen QUAlity Standards, or SEO experts), I wouldn't blame the use of it, just propose a recommendation in case of disallow instructions.

**Comment by floatingatoll** [comment]
I read over the guidelines and they specifically indicate that robots.txt should be used for two purposes only, neither related to web security. I don't think it makes much sense to create a security check out of something that should not be used for web security.
