### ISSUE TITLE
Provide notifications for new HTTPS sites

### ISSUE THREAD

**Issue by bifurcation** [mozilla/http-observatory-website#88]
I would like to be able to use the observatory to stay abreast of what sites are deploying HTTPS.  It would be useful if the observatory could:

1. Scan the top N websites every day or so (for say N=10^4)
2. Send an email or call a webhook when there's a change in HTTPS support

**Comment by floatingatoll** [comment]
While the observatory code has the capability to log historical reports in a database, it does not have any 'comparison' function that would offer what you seek, nor any 'notification' functions. The public website is not likely to be of use for your request.

You should, instead, run a local instance of the Observatory yourself. `mozilla/http-observatory/README` has more information. It's easy enough to set up, and once you've done so, you can directly query the database to detect when changes occur.

**Comment by april** [comment]
This was for a project that @bifurcation was working on, but now that he's no longer at Mozilla, is it still needed?
