### ISSUE TITLE
Make it easier to see what bonus points are up for grabs

### ISSUE THREAD

**Issue by edmorley** [mozilla/http-observatory-website#89]
Some of the tests have bonus points available (ie the score can be positive, not just negative). However if a test is marked as passing (score=0) then it's hard to know that there are actually extra bonus points up for grab.

For example on:
https://observatory.mozilla.org/analyze.html?host=treeherder.mozilla.org

The "HTTP Strict Transport Security" line has a score of zero, and a tick next to "Pass", which would imply all available points are already achieved.

However reading the source, I see it could get another +5 from preloading (the practicality of doing that on this specific domain right now aside):
https://github.com/mozilla/http-observatory/blob/8672f8c92990ab8fee68e4c6c72f1775c9b6b064/httpobs/scanner/grader/grade.py#L240-L243

Possible solutions:
* Don't display the tick under the "Pass" column, but display the dash ("-")
* In the rollover help text, mention the bonus
* Mention the bonus in a "what to fix next" (#86)

**Comment by april** [comment]
Good idea; I may also add a FAQ entry in the interim that accomplishes this.
