### ISSUE TITLE
test results mix test scope of aplicability

### ISSUE THREAD

**Issue by hwine** [mozilla/http-observatory-website#9]
There are two scopes for the findings being presented: "host based" and "page based" (cookies, subresource, etc.). The host scope would hold for every page within the site, but the page scope does not. Yet the 2 scopes are commingled in the "Test Scores" section.

I'd suggest grouping the test results by scope (host first). And include some sort of disclaimer on the page scope section that it *only* applies to the default page at the root of the site. Other pages on the site could have a different grade.

**Comment by marumari** [comment]
Many sites have differing headers depending on the resource type and location of files.  Even my personal site serves a different CSP header for SVG files than it does for the rest of the site.  And some of these, such as the CORS check are for multiple files contained on the site.  I'm not sure it's worth the complexity points to split them up.

There is a bug open to be able to test subresources; when that is completed, you will be able to see a grade for a different portion of your site.  :)

**Comment by marumari** [comment]
Note that this is the bug in question:

https://github.com/mozilla/http-observatory/issues/76

**Comment by hwine** [comment]
Exactly! Which is why I think splitting the results into "site" vs. "resource" makes sense. ;)  I'm fine to close this as a duplicate of the other bug, as I can't imagine how you wouldn't solve the issue with that.
