### ISSUE TITLE
[Feature] detection of rel="noopener noreferrer" on target="_blank" links

### ISSUE THREAD

**Issue by nico3333fr** [mozilla/http-observatory-website#94]
Hi there,

I wonder if it could be possible to add a test that detects every link with a ```target="_blank"``` also have ```rel="noopener noreferrer"``` ? (See https://mathiasbynens.github.io/rel-noopener/ for example of security issue that it creates)

Thanks a lot for reading this ;)
Nicolas

**Comment by marumari** [comment]
Not a bad idea.  I'll add it to the list of things to test for.  :)

**Comment by marumari** [comment]
Moved the issue to the right repo, though.  :)
