### ISSUE TITLE
HSTS minAge does not follow the https://hstspreload.org guideline

### ISSUE THREAD

**Issue by Pomax** [mozilla/http-observatory-website#96]
https://hstspreload.org notes that the minimum value for HSTS age headers should be 18 weeks, whereas Observatory goes with half a year. It would be worth changing Observatory to match the 18 week requirement instead, so that websites that follow https://hstspreload.org guidelines aren't penalized for doing the right thing.

**Comment by marumari** [comment]
If anything, the Observatory may be changed to increase its requirement to one or two years.  At this point, it is unlikely that we would decrease what we are looking for.

@lgarron, do we ever want to consider raising the minimum on hstspreload.org?

**Comment by Pomax** [comment]
Yeah in that case updating htstspreload.org to be in line with Observatory would be a good idea. Basically whatever results in "the same information" so guidelines don't conflict =)

**Comment by floatingatoll** [comment]
Moved to mozilla/http-observatory#232.
